{{- if .Values.webeoc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "webeoc.fullname" . }}
  labels:
    {{- include "webeoc.labels" . | nindent 4 }}
spec:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: "25Mi"
    storageClassName: netapp-file-standard
{{- end }}
