{{- if .Values.webeoc.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webeoc.fullname" . }}
  labels:
    {{- include "webeoc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webeoc.service.type }}
  ports:
    - port: {{ .Values.webeoc.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "webeoc.selectorLabels" . | nindent 4 }}
{{- end }}
