export const CONFIGURATION_CODES = {
  HWCTMPLATE: "HWCTMPLATE",
  ERSTMPLATE: "ERSTMPLATE",
  CEEBTMPLATE: "CEEBTMPLAT",
  CDTABLEVER: "CDTABLEVER",
  DFLTPAGNUM: "DFLTPAGNUM",
  MAXFILESZ: "MAXFILESZ",
};
