export const ORDER_DIRECTION = {
  ASC: "ASC",
  DESC: "DESC",
};

export const WEBEOC_REPORT_TYPE = {
  HWCR: "HWCR",
  ERS: "ERS",
};

export const CONFIGURATION_CODES = {
  HWCTMPLATE: "HWCTMPLATE",
  ERSTMPLATE: "ERSTMPLATE",
  CDTABLEVER: "CDTABLEVER",
  DFLTPAGNUM: "DFLTPAGNUM",
  MAXFILESZ: "MAXFILESZ",
};
