export const ORDER_DIRECTION = {
  ASC: "ASC",
  DESC: "DESC",
};

export const WEBEOC_REPORT_TYPE = {
  HWCR: "HWCR",
  ERS: "ERS",
  GIR: "GIR",
};

export const ACTION_TAKEN_ACTION_TYPES = {
  CREATE_ACTION_TAKEN: "ACTIONCTE",
  UPDATE_ACTION_TAKEN: "ACTIONUPD",
};

export const ACTION_TAKEN_TYPES = {
  ACTION_TAKEN: "ACTION-TAKEN",
  ACTION_TAKEN_UPDATE: "ACTION-TAKEN-UPDATE",
};
