apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metabase.fullname" . }}
  labels:
    {{- include "metabase.labels" . | nindent 4 }}
spec:
  strategy:
    type: {{ .Values.metabase.deploymentStrategy }}
  {{- if not .Values.metabase.autoscaling.enabled }}
  replicas: {{ .Values.metabase.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "metabase.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.metabase.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "metabase.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.metabase.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "metabase.fullname" . }}
          securityContext:
            {{- toYaml .Values.metabase.securityContext | nindent 12 }}
          image: "image-registry.openshift-image-registry.svc:5000/{{.Release.Namespace}}/{{ include "metabase.fullname" . }}:{{ .Values.metabase.metabaseImage.tag }}"
          imagePullPolicy: {{ .Values.metabase.image.pullPolicy }}
          env:
            - name: MB_DB_DBNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-metabase
                  key: databaseName
            - name: MB_DB_PORT
              value: "5432"
            - name: MB_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-metabase
                  key: databaseHost
            - name: MB_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-metabase
                  key: databaseUser
            - name: MB_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-metabase
                  key: databasePassword
            - name: MB_DB_TYPE
              value: postgres
            - name: TZ
              value: America/Vancouver
            - name: MB_ENCRYPTION_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-metabase
                  key: databasePassword
            - name: DB_PORT
              value: "5432"
            - name: MB_JETTY_HOST
              value: 0.0.0.0
            - name: MB_PASSWORD_COMPLEXITY
              value: strong
          ports:
            - name: http
              containerPort: {{ .Values.metabase.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 120
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 50
          resources:
            {{- toYaml .Values.metabase.resources | nindent 12 }}

      {{- with .Values.metabase.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metabase.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metabase.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}