{{- if and .Values.metabase.enabled .Values.metabase-pg.enabled }}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "metabase.fullname" . }}
  labels:
    {{- include "metabase.labels" . | nindent 4 }}
spec:
  lookupPolicy:
    local: false
  tags:
    - name: "{{ .Values.metabase.metabaseImage.tag }}"
      from:
        kind: DockerImage
        name: "{{ .Values.metabase.image.repository }}:{{ .Values.metabase.metabaseImage.tag }}"
      referencePolicy:
        type: Local
{{- end }}