{{- if and .Values.metabase.enabled }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    {{- include "metabase.labels" . | nindent 4 }}
  name: {{ include "metabase.fullname" . }}
spec:
  host: {{ include "metabase.route" . }}
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ include "metabase.fullname" . }}
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}