{{- if and .Values.metabase.enabled .Values.metabase-pg.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "metabase.fullname" . }}
  labels:
    {{- include "metabase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metabase.service.type }}
  ports:
    - port: {{ .Values.metabase.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "metabase.selectorLabels" . | nindent 4 }}
{{- end }}