{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  automountServiceAccountToken: false
  strategy:
    type: {{ .Values.frontend.deploymentStrategy }}
  {{- if not .Values.frontend.autoscaling.enabled }}
  replicas: {{ .Values.frontend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        prometheus.io/scrape: 'true'
        prometheus.io/port: '3003'
        prometheus.io/path: '/metrics'
      labels:
        {{- include "frontend.labels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      {{- if .Values.frontend.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.frontend.podSecurityContext | nindent 12 }}
      {{- end }}
      containers:
        - name: {{ include "frontend.fullname" . }}
          securityContext:
            capabilities:
              add: [ "NET_BIND_SERVICE" ]
          image: "{{.Values.global.registry}}/{{.Values.global.repository}}/frontend:{{ .Values.global.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ default "Always" .Values.frontend.imagePullPolicy }}
          env:
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
            - name: BACKEND_URL
              value: "http://{{ .Release.Name }}-backend"
            - name: GRAPHQL_URL
              value: "http://dc0a4a-compenf-dev-static-backend.apps.emerald.devops.gov.bc.ca"
            - name: LOG_LEVEL
              value: "info"
            - name: KEYCLOAK_URL
              valueFrom:
                secretKeyRef:
                  name: react-app
                  key: keycloak-url
            - name: COMS_URL
              valueFrom:
                secretKeyRef:
                  name: react-app
                  key: coms-url
            - name: COMS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: react-app
                  key: coms-bucket
            - name: ENVIRONMENT_NAME
              valueFrom:
                secretKeyRef:
                  name: react-app
                  key: environment-name
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          startupProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 4
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 2
            failureThreshold: 30
          #-- the liveness probe for the container. it is optional and is an object. for default values check this link: https://github.com/bcgov/helm-service/blob/main/charts/component/templates/deployment.yaml#L324-L328
          livenessProbe:
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              path: /health
              port: 3001
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 30m
              memory: 50Mi
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          emptyDir: {}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - {{ include "frontend.fullname" . }}
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"

{{- end }}
