apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: ${NAME}-${ZONE}
  app.kubernetes.io/part-of: ${NAME}-${ZONE}
parameters:
  - name: NAME
    description: Module name
    value: nr-compliance-enforcement
  - name: COMPONENT
    description: Component name
    value: webeoc
  - name: ZONE
    description: Deployment zone, e.g. pr-### or prod
    required: true
  - name: IMAGE_TAG
    description: Image tag to use
    value: latest
  - name: DOMAIN
    value: apps.silver.devops.gov.bc.ca
  - name: CPU_REQUEST
    value: "40m"
  - name: MEMORY_REQUEST
    value: "75Mi"
  - name: CPU_LIMIT
    value: "80m"
  - name: MEMORY_LIMIT
    value: "150Mi"
  - name: MIN_REPLICAS
    description: The minimum amount of replicas for the horizontal pod autoscaler.
    value: "2"
  - name: MAX_REPLICAS
    description: The maximum amount of replicas for the horizontal pod autoscaler.
    value: "3"
  - name: REGISTRY
    description: Container registry to import from (internal is image-registry.openshift-image-registry.svc:5000)
    value: ghcr.io
  - name: PROMOTE
    description: Image (namespace/name:tag) to promote/import
    value: bcgov/nr-compliance-enforcement/webeoc:prod
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: ${NAME}-${ZONE}
      name: ${NAME}-${ZONE}-${COMPONENT}
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: ${IMAGE_TAG}
          from:
            kind: DockerImage
            name: ${REGISTRY}/${PROMOTE}
          referencePolicy:
            type: Local
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${NAME}-${ZONE}
      name: ${NAME}-${ZONE}-${COMPONENT}
    spec:
      replicas: 1
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}
            from:
              kind: ImageStreamTag
              name: ${NAME}-${ZONE}-${COMPONENT}:${IMAGE_TAG}
      selector:
        deploymentconfig: ${NAME}-${ZONE}-${COMPONENT}
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            app: ${NAME}-${ZONE}
            deploymentconfig: ${NAME}-${ZONE}-${COMPONENT}
        spec:
          containers:
            - image: ${NAME}-${ZONE}-${COMPONENT}:${IMAGE_TAG}
              imagePullPolicy: Always
              name: ${NAME}
              env:
                - name: NODE_TLS_REJECT_UNAUTHORIZED
                  value: "0"
                - name: NATS_HOST
                  value: nats://${NAME}-${ZONE}-nats:4222
                - name: COMPLAINTS_MANAGEMENT_API_URL
                  value: https://${NAME}-${ZONE}-backend.${DOMAIN}/v1
                - name: COMPLAINTS_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: webeoc
                      key: complaints-api-key
                - name: WEBEOC_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: webeoc
                      key: webeoc-username
                - name: WEBEOC_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: webeoc
                      key: webeoc-password
                - name: WEBEOC_POSITION
                  valueFrom:
                    secretKeyRef:
                      name: webeoc
                      key: webeoc-position
                - name: WEBEOC_INCIDENT
                  valueFrom:
                    secretKeyRef:
                      name: webeoc
                      key: webeoc-incident
                - name: WEBEOC_URL
                  valueFrom:
                    secretKeyRef:
                      name: webeoc
                      key: webeoc-url
                - name: WEBEOC_COMPLAINT_HISTORY_DAYS
                  valueFrom:
                    secretKeyRef:
                      name: webeoc
                      key: webeoc-complaint-history-days
                - name: WEBEOC_CRON_EXPRESSION
                  valueFrom:
                    secretKeyRef:
                      name: webeoc
                      key: webeoc-cron-expression
              ports:
                - containerPort: 3002
                  protocol: TCP
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
              readinessProbe:
                httpGet:
                  path: /health
                  port: 3002
                  scheme: HTTP
                initialDelaySeconds: 60
                periodSeconds: 15
                timeoutSeconds: 5
              livenessProbe:
                successThreshold: 1
                failureThreshold: 3
                httpGet:
                  path: /health
                  port: 3002
                  scheme: HTTP
                initialDelaySeconds: 60
                periodSeconds: 30
                timeoutSeconds: 5
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${NAME}-${ZONE}
      name: ${NAME}-${ZONE}-${COMPONENT}
    spec:
      ports:
        - name: 3002-tcp
          protocol: TCP
          port: 80
          targetPort: 3002
      selector:
        deploymentconfig: ${NAME}-${ZONE}-${COMPONENT}
  - apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    metadata:
      name: ${NAME}-${ZONE}-${COMPONENT}
    spec:
      scaleTargetRef:
        apiVersion: apps.openshift.io/v1
        kind: DeploymentConfig
        name: ${NAME}-${ZONE}-${COMPONENT}
      minReplicas: ${{MIN_REPLICAS}}
      maxReplicas: ${{MAX_REPLICAS}}
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 100
