{{- if .Values.nats.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nats.fullname" . }}-pvc
  labels:
    {{- include "nats.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.nats.config.jetstream.fileStore.pvc.size }}
{{- end }}