{{- if .Values.nats.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nats.fullname" . }}
  labels:
    {{- include "nats.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "nats.selectorLabels" . | nindent 4 }}
  ports:
    - name: nats
      port: 4222
      protocol: TCP
      targetPort: 4222
{{- end }}