{{- if .Values.nats.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webeoc.fullname" . }}
  labels:
    {{- include "webeoc.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    {{- include "nats.selectorLabels" .Subcharts.nats | nindent 4 }}
  ports:
    - name: nats
      port: 4222
      protocol: TCP
      targetPort: 4222
{{- end }}