{{- if .Values.backup.enabled }}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "backup.fullname" . }}
  labels:
    {{- include "backup.labels" . | nindent 4 }}
spec:
  lookupPolicy:
    local: false
  tags:
    - name: "{{ .Values.backup.image.tag | default .Chart.AppVersion }}"
      from:
        kind: DockerImage
        name: "{{ .Values.backup.image.repository }}:{{ .Values.backup.image.tag | default .Chart.AppVersion }}"
      referencePolicy:
        type: Local

{{- end }}