-- V###__recreate_exhibit_with_property_fields.sql

DROP TABLE IF EXISTS investigation.exhibit;

CREATE TABLE
    investigation.exhibit (
        exhibit_guid UUID PRIMARY KEY DEFAULT public.uuid_generate_v4 (),
        task_guid UUID NOT NULL,
        investigation_guid UUID NOT NULL,
        exhibit_number INT NOT NULL,
        exhibit_display_number VARCHAR(64) NOT NULL,
        property_type CHAR(1) NOT NULL,
        description_text TEXT NOT NULL,
        quantity_amount INTEGER,
        seized_from_first_name VARCHAR(128),
        seized_from_last_name VARCHAR(128),
        seized_from_address VARCHAR(256),
        seized_from_phone_number VARCHAR(16),
        collected_utc_timestamp timestamp without time zone NOT NULL DEFAULT now (),
        collected_by_app_user_guid_ref UUID NOT NULL,
        location_of_intake_text TEXT,
        property_tag_number VARCHAR(64) NOT NULL,
        active_ind BOOLEAN NOT NULL DEFAULT TRUE,
        create_user_id VARCHAR(32) NOT NULL,
        create_utc_timestamp timestamp without time zone DEFAULT now () NOT NULL,
        update_user_id VARCHAR(32),
        update_utc_timestamp timestamp without time zone,
        CONSTRAINT fk_exhibit__task FOREIGN KEY (task_guid) REFERENCES investigation.task (task_guid),
        CONSTRAINT fk_exhibit__investigation FOREIGN KEY (investigation_guid) REFERENCES investigation.investigation (investigation_guid),
        CONSTRAINT uq_exhibit_number_per_task UNIQUE (task_guid, exhibit_number),
        CONSTRAINT chk_exhibit_property_type CHECK (property_type IN ('S', 'F'))
    );

COMMENT ON TABLE investigation.exhibit IS 'An investigation task can have many exhibits. An exhibit is a physical or digital item collected as evidence during the course of an investigation task.';

COMMENT ON COLUMN investigation.exhibit.exhibit_guid IS 'Primary key. System generated unique key for exhibits. This key should never be exposed to users via any system utilizing the tables.';

COMMENT ON COLUMN investigation.exhibit.task_guid IS 'Foreign key references investigation.task.task_guid. System generated unique key for tasks. This key should never be exposed to users via any system utilizing the tables.';

COMMENT ON COLUMN investigation.exhibit.investigation_guid IS 'Foreign key references investigation.investigation.investigation_guid. Denormalized from task to support querying exhibits at the investigation level. This key should never be exposed to users via any system utilizing the tables.';

COMMENT ON COLUMN investigation.exhibit.exhibit_number IS 'System generated incremental exhibit number, sequential within the task. Generated by the application on insert. Used as the numeric sort key.';

COMMENT ON COLUMN investigation.exhibit.exhibit_display_number IS 'System generated full display number, composed at insert as investigation name - task number - zero-padded exhibit number (e.g. INV26-001234-5-001). Stored to support sorting and searching on the full number. Treated as a snapshot; not recomputed if the investigation name changes.';

COMMENT ON COLUMN investigation.exhibit.property_type IS 'The type of property the exhibit represents. S = Seized, F = Found.';

COMMENT ON COLUMN investigation.exhibit.description_text IS 'A description of the exhibit collected during the investigation task.';

COMMENT ON COLUMN investigation.exhibit.quantity_amount IS 'The optional quantity of the item collected.';

COMMENT ON COLUMN investigation.exhibit.seized_from_first_name IS 'The first name of the person the item was seized from. Populated only when property_type is S (Seized). Captured as contact information for returning the item and is not tied to a party.';

COMMENT ON COLUMN investigation.exhibit.seized_from_last_name IS 'The last name of the person the item was seized from. Populated only when property_type is S (Seized). Captured as contact information for returning the item and is not tied to a party.';

COMMENT ON COLUMN investigation.exhibit.seized_from_address IS 'The address of the person the item was seized from. Populated only when property_type is S (Seized). Captured as contact information for returning the item and is not tied to a party.';

COMMENT ON COLUMN investigation.exhibit.seized_from_phone_number IS 'The phone number of the person the item was seized from. Populated only when property_type is S (Seized). Captured as contact information for returning the item and is not tied to a party.';

COMMENT ON COLUMN investigation.exhibit.collected_utc_timestamp IS 'The date and time the exhibit was collected (date/time of intake). Defaults to the current timestamp. The timestamp is stored in UTC with no offset.';

COMMENT ON COLUMN investigation.exhibit.collected_by_app_user_guid_ref IS 'Unenforced foreign key references shared.app_user_guid. GUID representing the officer that collected the exhibit. Defaults to the logged in user at time of creation. This key should never be exposed to users via any system utilizing the tables.';

COMMENT ON COLUMN investigation.exhibit.location_of_intake_text IS 'The free-form location where the exhibit was collected. This is the location of intake, not where the exhibit is stored.';

COMMENT ON COLUMN investigation.exhibit.property_tag_number IS 'The property tag number assigned to the exhibit.';

COMMENT ON COLUMN investigation.exhibit.active_ind IS 'A boolean indicator to determine if the exhibit is active. Inactive values are still retained in the system for legacy data integrity.';

COMMENT ON COLUMN investigation.exhibit.create_user_id IS 'The id of the user that created the exhibit record.';

COMMENT ON COLUMN investigation.exhibit.create_utc_timestamp IS 'The timestamp when the exhibit record was created. The timestamp is stored in UTC with no offset.';

COMMENT ON COLUMN investigation.exhibit.update_user_id IS 'The id of the user that last updated the exhibit record.';

COMMENT ON COLUMN investigation.exhibit.update_utc_timestamp IS 'The timestamp when the exhibit record was last updated. The timestamp is stored in UTC with no offset.';

CREATE TABLE
  exhibit_h (
    h_exhibit_guid uuid DEFAULT uuid_generate_v4 () NOT NULL,
    target_row_id uuid NOT NULL,
    operation_type character(1) NOT NULL,
    operation_user_id character varying(32) DEFAULT CURRENT_USER NOT NULL,
    operation_executed_at timestamp without time zone DEFAULT now () NOT NULL,
    data_after_executed_operation jsonb
  );

COMMENT ON TABLE exhibit_h IS 'Stores the audit history for exhibit records.';

COMMENT ON COLUMN exhibit_h.h_exhibit_guid IS 'The system-generated unique identifier for the exhibit history record.';

COMMENT ON COLUMN exhibit_h.target_row_id IS 'The unique identifier of the exhibit record affected by the operation.';

COMMENT ON COLUMN exhibit_h.operation_type IS 'The type of database operation executed on the exhibit record. For example I = Insert, U = Update, D = Delete.';

COMMENT ON COLUMN exhibit_h.operation_user_id IS 'The id of the user that executed the operation.';

COMMENT ON COLUMN exhibit_h.operation_executed_at IS 'The timestamp when the operation was executed. The timestamp is stored in UTC with no Offset.';

COMMENT ON COLUMN exhibit_h.data_after_executed_operation IS 'A JSON representation of the exhibit record after the operation was executed.';

CREATE TRIGGER exhibit_history_trigger
BEFORE INSERT OR DELETE OR UPDATE
ON exhibit
FOR EACH ROW
EXECUTE FUNCTION audit_history (
  'exhibit_h',
  'exhibit_guid'
);
