type Contravention {
  contraventionIdentifier: String!
  investigationIdentifier: String!
  legislationIdentifierRef: String!
  investigationParty: [InvestigationParty]
  isActive: Boolean!
  date: DateTime
  community: String
  speciesCode: String
  speciesOtherText: String
  quantity: Int
  wildlifeManagementUnitCode: String
}

input CreateUpdateContraventionInput {
  investigationGuid: String!
  investigationPartyGuids: [String]
  legislationReference: String!
  date: DateTime
  community: String
  selectedPartyGuid: String
  speciesCode: String
  speciesOtherText: String
  quantity: Int
  wildlifeManagementUnitCode: String
}
