import { createSlice } from "@reduxjs/toolkit";
import { RootState, AppThunk } from "../store";
import {
  deleteMethod,
  generateApiParameters,
  get,
  putFile,
} from "../../common/api";
import { from } from "linq-to-typescript";
import { COMSObject } from "../../types/coms/object";
import { AttachmentsState } from "../../types/state/attachments-state";
import config from "../../../config";
import { getThumbnailFile, injectComplaintIdentifierToFilename, injectComplaintIdentifierToThumbFilename, isImage } from "../../common/methods";
import { ToggleError, ToggleSuccess } from "../../common/toast";
import axios from "axios";

const initialState: AttachmentsState = {
  attachments: [],
};

/**
 * Attachments for each complaint
 */
export const attachmentsSlice = createSlice({
  name: "attachments",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {

    // used when retrieving attachments from objectstore
    setAttachments: (state, action) => {
      const {
        payload: { attachments },
      } = action;
      return { ...state, attachments: attachments ?? [] };
    },

    // used when removing an attachment from a complaint
    removeAttachment: (state, action) => {
      return {
        ...state,
        attachments: state.attachments.filter(attachment => attachment.id !== action.payload),
      };
    },

    // used when adding an attachment to a complaint
    addAttachment: (state, action) => {
      const { name, type, size, id } = action.payload; // Extract relevant info
      const serializedFile = { name, type, size, id }; 

      return {
        ...state,
        attachments: [...state.attachments, serializedFile],
      };
    },
    
  },

  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {},
});

// export the actions/reducers
export const { setAttachments, removeAttachment , addAttachment} = attachmentsSlice.actions;

// Get list of the attachments and update store
export const getAttachments =
  (complaint_identifier: string): AppThunk =>
  async (dispatch) => {
    try {
      const parameters = generateApiParameters(
        `${config.COMS_URL}/object?bucketId=${config.COMS_BUCKET}`
      );
      const response = await get<Array<COMSObject>>(dispatch, parameters, {
        "x-amz-meta-complaint-id": complaint_identifier,
        "x-amz-meta-is-thumb": "N",
      });
      if (response && from(response).any()) {
        for(let attachment of response)
        {
          //try{
          if(isImage(attachment.name))
          {
            const thumbArrayResponse = await get<Array<COMSObject>>(dispatch, parameters, {
              "x-amz-meta-complaint-id": complaint_identifier,
              "x-amz-meta-is-thumb": "Y",
              "x-amz-meta-thumb-for": attachment?.id,
            });
            
            if(thumbArrayResponse[0]?.id)
            {
              const thumbParameters = generateApiParameters(
                `${config.COMS_URL}/object/${thumbArrayResponse[0]?.id}?download=url`
              );
          
              const thumbResponse = await get<string>(dispatch, thumbParameters);
              attachment.imageIconString = thumbResponse;
              attachment.imageIconId = thumbArrayResponse[0]?.id;
              }
          }

          /*}catch (error) {
            console.log("getThumbError: " + error);
            ToggleError(`Error retrieving thumbnail`);
          }*/
        }
        
        dispatch(
          setAttachments({
            attachments: response ?? [],
          })
        );
      }
    } catch (error) {
      ToggleError(`Error retrieving attachments`);
    }
  };

// delete attachments from objectstore
export const deleteAttachments =
  (attachments: COMSObject[]): AppThunk =>
  async (dispatch) => {
    if (attachments) {
      for (const attachment of attachments) {
        try {
          const parameters = generateApiParameters(
            `${config.COMS_URL}/object/${attachment.id}`
          );

          await deleteMethod<string>(dispatch, parameters);
          dispatch(removeAttachment(attachment.id)); // delete from store
          if(isImage(attachment.name))
          {
            const thumbParameters = generateApiParameters(
              `${config.COMS_URL}/object/${attachment.imageIconId}`
            );

            await deleteMethod<string>(dispatch, thumbParameters);
          }
          ToggleSuccess(`Attachment ${decodeURIComponent(attachment.name)} has been removed`);
        } catch (error) {
          ToggleError(`Attachment ${decodeURIComponent(attachment.name)} could not be deleted`);
        }
      }
    }

  };

// save new attachment(s) to object store
export const saveAttachments =
  (attachments: File[], complaint_identifier: string): AppThunk =>
  async (dispatch) => {

    if (!attachments) {
      return;
    }

    for (const attachment of attachments) {
      const header = {
        "x-amz-meta-complaint-id": complaint_identifier,
        "x-amz-meta-is-thumb": "N",
        "Content-Disposition": `attachment; filename="${encodeURIComponent(injectComplaintIdentifierToFilename(
          attachment.name,
          complaint_identifier
        ))}"`,
        "Content-Type": attachment?.type,
      };

      try {
        const parameters = generateApiParameters(
          `${config.COMS_URL}/object?bucketId=${config.COMS_BUCKET}`
        );
        const response = await putFile<COMSObject>(
          dispatch,
          parameters,
          header,
          attachment
        );
        dispatch(addAttachment(response)); // dispatch with serializable payload
        if(isImage(attachment.name))
        {
          const thumbHeader = {
            "x-amz-meta-complaint-id": complaint_identifier,
            "x-amz-meta-is-thumb": "Y",
            "x-amz-meta-thumb-for": response.id,
            "Content-Disposition": `attachment; filename="${encodeURIComponent(injectComplaintIdentifierToThumbFilename(
              attachment.name,
              complaint_identifier
            ))}"`,
            "Content-Type": "image/jpeg",
          };  

          const thumbnailFile = await getThumbnailFile(attachment).catch(error => {
            //we are just going to ignore this and move on
            console.error('Error occurred while getting thumbnail file:', error);
          });

          if (thumbnailFile) {
            await putFile<COMSObject>(
              dispatch,
              parameters,
              thumbHeader,
              thumbnailFile
            );
          }
        }

        if (response) {
          ToggleSuccess(`Attachment "${attachment.name}" saved`);
        }

      } catch (error) {
        if (axios.isAxiosError(error) && error.response?.status === 409) {
          ToggleError(`Attachment "${attachment.name}" could not be saved.  Duplicate file.`);
        } else {
          ToggleError(`Attachment "${attachment.name}" could not be saved.`);
        }
      }
    }
  };

//-- selectors
export const selectAttachments = (state: RootState): COMSObject[]  => {
  const { attachments: attachmentsRoot } = state;
  const { attachments } = attachmentsRoot;

  return attachments ?? [];
};

export default attachmentsSlice.reducer;
