import { AppThunk, RootState } from "@store/store";
import { generateApiParameters, get } from "@common/api";
import { COMSObject } from "@apptypes/coms/object";
import config from "@/config";
import { ToggleError, ToggleSuccess, ToggleWarning } from "@common/toast";
import * as zip from "@zip.js/zip.js";
import { AUTH_TOKEN } from "@/app/service/user-service";
import { BulkDownloadState, CurrentDownload } from "@/app/types/state/bulk-download-state";
import { createSlice } from "@reduxjs/toolkit";
import AttachmentEnum from "@constants/attachment-enum";
import { fetchObjectsMetadata } from "@common/attachment-utils";

const initialState: BulkDownloadState = {
  isBulkDownloadInProgress: false,
  currentDownload: null,
};

export const bulkDownloadSlice = createSlice({
  name: "bulkDownload",
  initialState,

  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setBulkDownloadInProgress: (state, action) => {
      const { isInProgress, downloadId } = action.payload;

      state.isBulkDownloadInProgress = isInProgress;

      if (isInProgress && downloadId !== undefined) {
        // Start new download
        state.currentDownload = {
          downloadId,
        };
      } else if (!isInProgress) {
        state.currentDownload = null;
      }
    },

    resetBulkDownload: (state) => {
      state.isBulkDownloadInProgress = false;
      state.currentDownload = null;
    },
  },

  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {},
});

export const { setBulkDownloadInProgress, resetBulkDownload } = bulkDownloadSlice.actions;

// Selectors
export const selectIsBulkDownloadInProgress = (state: RootState): boolean => {
  return state.bulkDownload.isBulkDownloadInProgress;
};

export const selectCurrentDownload = (state: RootState): CurrentDownload | null => {
  return state.bulkDownload.currentDownload;
};

export default bulkDownloadSlice.reducer;

//Thunks
export interface FileWithPresignedUrl {
  id: string | undefined;
  name: string;
  size: number;
  url: string;
  folder?: string;
}

export interface BulkDownloadProgressEvent {
  fileIndex: number;
  fileCount: number;
  overallPercent: number;
  fileName: string;
  retryAttempt?: number;
  phase: "downloading" | "compressing" | "finalizing";
}

export type BulkDownloadProgressCallback = (event: BulkDownloadProgressEvent) => void;

export const configureZipJs = () => {
  zip.configure({
    useWebWorkers: true,
  });
};

import { RETRY_CONFIG, categorizeError, withRetry } from "@common/attachment-utils";

const CONFIG = {
  ...RETRY_CONFIG,
  MEMORY_CLEANUP_DELAY_MS: 1500, // Pause between files for memory cleanup
  MEMORY_HIGH_THRESHOLD: 80, // Warn if memory > 80%
  PRESIGNED_URL_EXPIRY_SECONDS: 86400, // 24 hours
};

/**
 * Main bulk download function thunk
 */
export const bulkDownload =
  (
    downloadId: string,
    attachments: COMSObject[],
    zipFilename: string,
    additionalFiles?: FileWithPresignedUrl[],
    onProgress?: BulkDownloadProgressCallback,
    attachmentType?: AttachmentEnum,
  ): AppThunk<Promise<void>> =>
  async (dispatch, getState) => {
    const isBulkDownloadInProgress = selectIsBulkDownloadInProgress(getState());

    // Prevent concurrent downloads
    if (isBulkDownloadInProgress) {
      ToggleError("A download is already in progress. Please wait.");
      return;
    }

    try {
      dispatch(
        setBulkDownloadInProgress({
          isInProgress: true,
          downloadId,
        }),
      );

      const authToken = localStorage.getItem(AUTH_TOKEN);
      if (!authToken) {
        ToggleError("Authentication required");
        return;
      }

      // Start download
      await bulkDownloadWithZipJs(
        attachments,
        authToken,
        zipFilename,
        dispatch,
        additionalFiles,
        onProgress,
        attachmentType,
      );
    } catch (error) {
      console.error("Bulk download error:", error);

      if (error instanceof Error) {
        if (error.message.includes("Out of memory") || error.message.includes("allocation failed")) {
          ToggleError(
            `Browser ran out of memory. Try:\n` +
              `• Close other tabs\n` +
              `• Download fewer files at once\n` +
              `• Use a desktop browser with more RAM`,
          );
        } else if (error.message.includes("quota")) {
          ToggleError("Browser storage quota exceeded. Please free up disk space.");
        } else if (error.message.includes("COMS API URL not configured")) {
          ToggleError("Configuration error: COMS API URL is missing. Please contact support.");
        } else {
          ToggleError(`Failed to download: ${error.message}`, { autoClose: false });
        }
      } else {
        ToggleError("Failed to download attachments. Please try again.", { autoClose: false });
      }
    } finally {
      dispatch(resetBulkDownload());
    }
  };

/**
 * Download and ZIP files using zip.js
 */
async function bulkDownloadWithZipJs(
  attachments: COMSObject[],
  authToken: string,
  zipFilename: string,
  dispatch?: any,
  additionalFiles?: FileWithPresignedUrl[],
  onProgress?: BulkDownloadProgressCallback,
  attachmentType?: AttachmentEnum,
): Promise<void> {
  // Get presigned URLs for all files concurrently
  const urlPromises = attachments.map(async (attachment, index) => {
    try {
      const url = `${config.COMS_URL}/object/${attachment.id}?download=url&expiresIn=${CONFIG.PRESIGNED_URL_EXPIRY_SECONDS}`;
      const params = generateApiParameters(url);

      let presignedUrl = await get<string>(dispatch, params);

      const response = await fetch(url, {
        method: "GET",
        headers: {
          Authorization: `Bearer ${authToken}`,
          "Content-Type": "application/json",
        },
      });

      if (!response.ok) {
        const errorText = await response.text().catch(() => "");
        throw new Error(`Failed to get URL for ${attachment.name}: HTTP ${response.status} - ${errorText ?? ""}`);
      }

      return {
        id: attachment.id,
        name: attachment.name,
        size: attachment.size || 0,
        url: presignedUrl.trim(),
        folder: attachment.folder,
      };
    } catch (error) {
      console.error(`Failed to get presigned URL for ${attachment.name}:`, error);
      throw error;
    }
  });

  let files: FileWithPresignedUrl[];

  try {
    files = await Promise.all(urlPromises);
  } catch (error) {
    console.error("Failed to get presigned URLs from COMS:", error);
    throw new Error(
      `Failed to get download URLs from COMS API. ${error instanceof Error ? error.message : "Please try again."}`,
    );
  }
  const additionalFileObjects: FileWithPresignedUrl[] = additionalFiles || [];
  files = [...files, ...additionalFileObjects];

  // Get any missing file sizes from the metadata
  if (
    attachmentType !== undefined &&
    files.some((f, i) => i < files.length - additionalFileObjects.length && !f.size)
  ) {
    files = await getFileSizes(files, additionalFileObjects.length, attachmentType);
  }

  //Create ZIP using zip.js
  await createZipWithZipJs(files, zipFilename, onProgress);
}

/**
 * Get file size from metadata
 */
async function getFileSizes(
  files: FileWithPresignedUrl[],
  additionalFileCount: number,
  attachmentType: AttachmentEnum,
): Promise<FileWithPresignedUrl[]> {
  const lookupCutoff = files.length - additionalFileCount;
  const idsToLookup: string[] = [];
  for (let i = 0; i < lookupCutoff; i++) {
    const f = files[i];
    if (f.id && !f.size) idsToLookup.push(f.id);
  }

  if (idsToLookup.length === 0) {
    return files;
  }

  try {
    const metadataMap = await fetchObjectsMetadata(idsToLookup, attachmentType);
    return files.map((file) => {
      if (!file.id || file.size) return file;
      const metadataSize = metadataMap.get(file.id)?.size;
      return metadataSize ? { ...file, size: metadataSize } : file;
    });
  } catch (error) {
    // Non-fatal — fall back to fraction-weighted progress.
    console.warn("Size metadata lookup failed:", error);
    return files;
  }
}

/**
 * Create ZIP file using zip.js
 */
async function createZipWithZipJs(
  files: FileWithPresignedUrl[],
  zipFilename: string,
  onProgress?: BulkDownloadProgressCallback,
): Promise<void> {
  // Create ZIP writer
  const zipWriter = new zip.ZipWriter(new zip.BlobWriter("application/zip"), {
    bufferedWrite: true,
    useCompressionStream: true,
  });

  let completedFiles = 0;
  let failedFiles = 0;
  let totalBytesProcessed = 0;
  const failedFileNames: string[] = [];

  const fileCount = files.length;
  const totalBytes = files.reduce((sum, f) => sum + (f.size || 0), 0);

  // If all file sizes are known use bytes to calculate download percent, otherwise use an equal weighting per file
  const allSizesKnown = fileCount > 0 && files.every((f) => (f.size || 0) > 0);
  const useByteWeighted = allSizesKnown && totalBytes > 0;
  const fileShare = fileCount > 0 ? 1 / fileCount : 0;
  let completedBytes = 0;
  let processedFileCount = 0;

  // Main processing loop
  for (let i = 0; i < fileCount; i++) {
    const file = files[i];
    const fileSizeHint = file.size || 0;

    const updateFileProgress = (loaded: number, contentLength: number, retryAttempt?: number) => {
      const fileTotal = contentLength > 0 ? contentLength : fileSizeHint;
      const fileFraction = fileTotal > 0 ? Math.min(1, loaded / fileTotal) : 0;

      let overallFraction: number;
      if (useByteWeighted) {
        const cappedLoaded = fileSizeHint > 0 ? Math.min(loaded, fileSizeHint) : loaded;
        overallFraction = (completedBytes + cappedLoaded) / totalBytes;
      } else {
        overallFraction = processedFileCount * fileShare + fileFraction * fileShare;
      }

      const overallPercent = Math.min(100, Math.round(overallFraction * 100));

      onProgress?.({
        fileIndex: i,
        fileCount,
        overallPercent,
        fileName: file.name,
        retryAttempt,
        phase: "downloading",
      });
    };

    updateFileProgress(0, 0);

    const showCompressing = () => {
      const overallFraction = useByteWeighted
        ? (completedBytes + fileSizeHint) / totalBytes
        : (processedFileCount + 1) * fileShare;
      onProgress?.({
        fileIndex: i,
        fileCount,
        overallPercent: Math.min(100, Math.round(overallFraction * 100)),
        fileName: file.name,
        phase: "compressing",
      });
    };

    try {
      const result = await processSingleFile(file, zipWriter, updateFileProgress, showCompressing);
      completedFiles++;
      processedFileCount++;
      completedBytes += fileSizeHint > 0 ? fileSizeHint : result.bytesProcessed;
      totalBytesProcessed += result.bytesProcessed;

      // Pause briefly between files to allow memory cleanup
      if (i + 1 < files.length) {
        await new Promise((resolve) => setTimeout(resolve, CONFIG.MEMORY_CLEANUP_DELAY_MS));
      }
    } catch (error) {
      processedFileCount++;
      completedBytes += fileSizeHint;
      failedFiles++;
      failedFileNames.push(file.name);

      console.error(`\nFAILED: ${file.name}`);
      console.error(`Final error: ${error instanceof Error ? error.message : String(error)}`);

      // Detailed error categorization
      if (error instanceof Error) {
        const { errorType } = categorizeError(error);
        console.error(`  → Type: ${errorType} ERROR`);
      }

      // Add error placeholder
      await addErrorPlaceholder(zipWriter, file, error, i, files.length);

      // Pause after error to allow memory recovery
      if (i + 1 < files.length) {
        await new Promise((resolve) => setTimeout(resolve, 3000));
      }
    }
  }

  // Summary
  showCompletionSummary(completedFiles, failedFiles, files.length, failedFileNames);

  // Signal that downloads are complete and we are now finalizing the zip
  onProgress?.({
    fileIndex: Math.max(fileCount - 1, 0),
    fileCount,
    overallPercent: 100,
    fileName: "",
    phase: "finalizing",
  });

  // Finalize zip
  const zipBlob = await zipWriter.close();

  // Trigger download
  const downloadUrl = globalThis.URL.createObjectURL(zipBlob);
  const link = document.createElement("a");
  link.href = downloadUrl;
  link.download = zipFilename;
  link.style.display = "none";

  document.body.appendChild(link);
  link.click();

  // Cleanup
  setTimeout(() => {
    link.remove();
    globalThis.URL.revokeObjectURL(downloadUrl);
  }, 1000);
}

// ==== HELPERS FUNCTIONS ====

function logMemory() {
  if ((performance as any).memory) {
    const mem = (performance as any).memory;
    const usedMB = (mem.usedJSHeapSize / 1024 / 1024).toFixed(0);
    const limitMB = (mem.jsHeapSizeLimit / 1024 / 1024).toFixed(0);
    const availableMB = ((mem.jsHeapSizeLimit - mem.usedJSHeapSize) / (1024 * 1024)).toFixed(0);
    const percentUsed = ((mem.usedJSHeapSize / mem.jsHeapSizeLimit) * 100).toFixed(1);

    if (Number.parseFloat(percentUsed) > CONFIG.MEMORY_HIGH_THRESHOLD) {
      console.warn(`Memory usage is HIGH (${percentUsed}%)`);
    }

    return {
      usedMB: Number.parseInt(usedMB),
      limitMB: Number.parseInt(limitMB),
      availableMB: Number.parseInt(availableMB),
      percentUsed: Number.parseFloat(percentUsed),
    };
  }
  return null;
}

async function downloadFileWithRetry(
  file: FileWithPresignedUrl,
  onFileProgress?: (loaded: number, contentLength: number, retryAttempt?: number) => void,
): Promise<{ success: boolean; blob?: Blob; error?: Error; attempts: number }> {
  const result = await withRetry(
    async (attempt) => {
      const attemptPrefix = attempt > 1 ? `[Retry ${attempt - 1}/${CONFIG.MAX_RETRIES - 1}]` : "  ";
      const retryAttempt = attempt > 1 ? attempt - 1 : undefined;

      // Reset per-file progress to 0 at the start of each attempt
      onFileProgress?.(0, 0, retryAttempt);

      // Check available memory before download
      if (attempt > 1) {
        const memInfo = logMemory();
        await checkMemoryBeforeDownload(memInfo, file, attemptPrefix);
      }

      // Download file
      const response = await fetch(file.url, { method: "GET" });

      if (!response.ok) {
        throw new Error(`HTTP ${response.status}: ${response.statusText}`);
      }

      const blob = await readResponseWithProgress(response, onFileProgress, retryAttempt);
      validateBlobSize(blob, file, attemptPrefix);

      return blob;
    },
    {
      onRetry: (attempt, error) => {
        const { errorType } = categorizeError(error);
        console.error(`[Attempt ${attempt}/${CONFIG.MAX_RETRIES}] ✗ Failed: ${error.message} (${errorType})`);
      },
    },
  );

  if (result.success) {
    return { success: true, blob: result.result, attempts: result.attempts };
  }

  console.error(`All ${CONFIG.MAX_RETRIES} attempts failed for ${file.name}`);
  return { success: false, error: result.error, attempts: result.attempts };
}

async function readResponseWithProgress(
  response: Response,
  onFileProgress?: (loaded: number, contentLength: number, retryAttempt?: number) => void,
  retryAttempt?: number,
): Promise<Blob> {
  const contentType = response.headers.get("content-type") || "application/octet-stream";
  const contentLengthHeader = response.headers.get("content-length");
  const contentLength = contentLengthHeader ? Number.parseInt(contentLengthHeader, 10) || 0 : 0;

  // If we cannot stream (no body or no progress callback), fall back to response.blob()
  if (!onFileProgress || !response.body || typeof (response.body as any).getReader !== "function") {
    return await response.blob();
  }

  onFileProgress(0, contentLength, retryAttempt);

  const reader = (response.body as ReadableStream<Uint8Array>).getReader();
  const chunks: BlobPart[] = [];
  let loaded = 0;

  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      if (value) {
        chunks.push(value as BlobPart);
        loaded += value.length;
        onFileProgress(loaded, contentLength, retryAttempt);
      }
    }
  } finally {
    try {
      reader.releaseLock();
    } catch {
      // Ignore — reader may already be released
    }
  }

  return new Blob(chunks, { type: contentType });
}

function validateBlobSize(blob: Blob, file: FileWithPresignedUrl, attemptPrefix: string): void {
  if (blob.size === 0) {
    throw new Error("Downloaded blob is 0 bytes");
  }

  if (file.size > 0) {
    const sizeDiff = Math.abs(blob.size - file.size);
    const sizePercentDiff = (sizeDiff / file.size) * 100;

    if (sizePercentDiff > 5) {
      console.warn(
        `${attemptPrefix} Size mismatch: Expected ${(file.size / (1024 * 1024)).toFixed(2)}MB, ` +
          `got ${(blob.size / (1024 * 1024)).toFixed(2)}MB (${sizePercentDiff.toFixed(1)}% diff)`,
      );
    }
  }
}

async function checkMemoryBeforeDownload(
  memInfo: any,
  file: FileWithPresignedUrl,
  attemptPrefix: string,
): Promise<void> {
  if (!memInfo) return;
  const neededMB = (file.size / (1024 * 1024)) * 1.5;
  if (memInfo.availableMB < neededMB) {
    console.warn(`${attemptPrefix} Low memory detected. Waiting 3s for cleanup...`);
    await new Promise((resolve) => setTimeout(resolve, 3000));
  }
}

async function processSingleFile(
  file: FileWithPresignedUrl,
  zipWriter: any,
  onFileProgress?: (loaded: number, contentLength: number, retryAttempt?: number) => void,
  onCompress?: () => void,
): Promise<{ success: boolean; bytesProcessed: number }> {
  // Download with retry
  const downloadResult = await downloadFileWithRetry(file, onFileProgress);

  if (!downloadResult.success || !downloadResult.blob) {
    throw downloadResult.error || new Error("Download failed");
  }

  const blob = downloadResult.blob;

  // Add to ZIP
  const skipCompression =
    /\.(mp4|mov|avi|mkv|flv|wmv|webm|m4v|mpg|mpeg|3gp|zip|rar|7z|gz|bz2|xz|tar|jpg|jpeg|png|gif|webp|bmp|ico|svg|mp3|m4a|aac|ogg|flac|wav|wma|pdf|epub|mobi)$/i.test(
      file.name,
    );
  const compressionLevel = skipCompression ? 0 : 1;

  // Show adding to zip message
  onCompress?.();

  const zipPath = file.folder ? `${file.folder}/${file.name}` : file.name;
  await zipWriter.add(zipPath, new zip.BlobReader(blob), {
    level: compressionLevel,
    bufferedWrite: true,
  });

  return { success: true, bytesProcessed: blob.size };
}

async function addErrorPlaceholder(
  zipWriter: any,
  file: FileWithPresignedUrl,
  error: unknown,
  index: number,
  totalFiles: number,
): Promise<void> {
  try {
    const errorMessage =
      `Failed to download this file after ${CONFIG.MAX_RETRIES} attempts\n\n` +
      `Filename: ${file.name}\n` +
      `Expected Size: ${(file.size / (1024 * 1024)).toFixed(2)}MB\n` +
      `Error: ${error instanceof Error ? error.message : String(error)}\n` +
      `Error Type: ${error instanceof Error ? error.constructor.name : typeof error}\n` +
      `Timestamp: ${new Date().toISOString()}\n` +
      `File Index: ${index + 1} of ${totalFiles}\n` +
      `Retry Attempts: ${CONFIG.MAX_RETRIES}\n\n`;

    const folderPrefix = file.folder ? `${file.folder}/` : "";
    const errorPath = `ERROR_${folderPrefix}${file.name}.txt`;
    await zipWriter.add(errorPath, new zip.TextReader(errorMessage), { level: 0 });
  } catch (placeholderError) {
    console.error(`Could not add error placeholder:`, placeholderError);
  }
}

function showCompletionSummary(
  completedFiles: number,
  failedFiles: number,
  totalFiles: number,
  failedFileNames: string[],
): void {
  if (failedFiles > 0) {
    console.log(`\n Failed files (after ${CONFIG.MAX_RETRIES} retry attempts each):`);
    failedFileNames.forEach((name, idx) => console.log(`    ${idx + 1}. ${name}`));

    ToggleWarning(
      `Downloaded ${completedFiles} of ${totalFiles} files. ` +
        `${failedFiles} failed after ${CONFIG.MAX_RETRIES} retry attempts.`,
      { autoClose: false },
    );
  } else {
    ToggleSuccess(`Successfully downloaded ${totalFiles} files.`, { autoClose: false });
  }
}
