import { AppThunk, RootState } from "@store/store";
import { generateApiParameters, get } from "@common/api";
import { COMSObject } from "@apptypes/coms/object";
import config from "@/config";
import { ToggleError, ToggleSuccess, ToggleWarning } from "@common/toast";
import * as zip from "@zip.js/zip.js";
import { AUTH_TOKEN } from "@/app/service/user-service";
import { BulkDownloadState, CurrentDownload } from "@/app/types/state/bulk-download-state";
import { createSlice } from "@reduxjs/toolkit";

const initialState: BulkDownloadState = {
  isBulkDownloadInProgress: false,
  currentDownload: null,
};

export const bulkDownloadSlice = createSlice({
  name: "bulkDownload",
  initialState,

  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setBulkDownloadInProgress: (state, action) => {
      const { isInProgress, taskId } = action.payload;

      state.isBulkDownloadInProgress = isInProgress;

      if (isInProgress && taskId !== undefined) {
        // Start new download
        state.currentDownload = {
          taskId,
        };
      } else if (!isInProgress) {
        state.currentDownload = null;
      }
    },

    resetBulkDownload: (state) => {
      state.isBulkDownloadInProgress = false;
      state.currentDownload = null;
    },
  },

  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {},
});

export const { setBulkDownloadInProgress, resetBulkDownload } = bulkDownloadSlice.actions;

// Selectors
export const selectIsBulkDownloadInProgress = (state: RootState): boolean => {
  return state.bulkDownload.isBulkDownloadInProgress;
};

export const selectCurrentDownload = (state: RootState): CurrentDownload | null => {
  return state.bulkDownload.currentDownload;
};

export default bulkDownloadSlice.reducer;

//Thunks
interface FileWithPresignedUrl {
  id: string | undefined;
  name: string;
  size: number;
  url: string;
}

export const configureZipJs = () => {
  zip.configure({
    useWebWorkers: true,
  });
};

import { RETRY_CONFIG, categorizeError, withRetry } from "@common/attachment-utils";

const CONFIG = {
  ...RETRY_CONFIG,
  MEMORY_CLEANUP_DELAY_MS: 1500, // Pause between files for memory cleanup
  MEMORY_HIGH_THRESHOLD: 80, // Warn if memory > 80%
  PRESIGNED_URL_EXPIRY_SECONDS: 86400, // 24 hours
};

/**
 * Main bulk download function thunk
 */
export const bulkDownload =
  (taskId: string, taskNumber: number, attachments: COMSObject[]): AppThunk =>
  async (dispatch, getState) => {
    const isBulkDownloadInProgress = selectIsBulkDownloadInProgress(getState());

    // Prevent concurrent downloads
    if (isBulkDownloadInProgress) {
      ToggleError("A download is already in progress. Please wait.");
      return;
    }

    try {
      dispatch(
        setBulkDownloadInProgress({
          isInProgress: true,
          taskId,
        }),
      );

      const authToken = localStorage.getItem(AUTH_TOKEN);
      if (!authToken) {
        ToggleError("Authentication required");
        return;
      }

      // Start download
      await bulkDownloadWithZipJs(taskId, taskNumber, attachments, authToken, dispatch);
    } catch (error) {
      console.error("Bulk download error:", error);

      if (error instanceof Error) {
        if (error.message.includes("Out of memory") || error.message.includes("allocation failed")) {
          ToggleError(
            `Browser ran out of memory. Try:\n` +
              `• Close other tabs\n` +
              `• Download fewer files at once\n` +
              `• Use a desktop browser with more RAM`,
          );
        } else if (error.message.includes("quota")) {
          ToggleError("Browser storage quota exceeded. Please free up disk space.");
        } else if (error.message.includes("COMS API URL not configured")) {
          ToggleError("Configuration error: COMS API URL is missing. Please contact support.");
        } else {
          ToggleError(`Failed to download: ${error.message}`, { autoClose: false });
        }
      } else {
        ToggleError("Failed to download attachments. Please try again.", { autoClose: false });
      }
    } finally {
      dispatch(resetBulkDownload());
    }
  };

/**
 * Download and ZIP files using zip.js
 */
async function bulkDownloadWithZipJs(
  taskId: string,
  taskNumber: number,
  attachments: COMSObject[],
  authToken: string,
  dispatch?: any,
): Promise<void> {
  // Get presigned URLs for all files concurrently
  const urlPromises = attachments.map(async (attachment, index) => {
    try {
      const url = `${config.COMS_URL}/object/${attachment.id}?download=url&expiresIn=${CONFIG.PRESIGNED_URL_EXPIRY_SECONDS}`;
      const params = generateApiParameters(url);

      let presignedUrl = await get<string>(dispatch, params);

      const response = await fetch(url, {
        method: "GET",
        headers: {
          Authorization: `Bearer ${authToken}`,
          "Content-Type": "application/json",
        },
      });

      if (!response.ok) {
        const errorText = await response.text().catch(() => "");
        throw new Error(`Failed to get URL for ${attachment.name}: HTTP ${response.status} - ${errorText ?? ""}`);
      }

      return {
        id: attachment.id,
        name: attachment.name,
        size: attachment.size || 0,
        url: presignedUrl.trim(),
      };
    } catch (error) {
      console.error(`Failed to get presigned URL for ${attachment.name}:`, error);
      throw error;
    }
  });

  let files: FileWithPresignedUrl[];

  try {
    files = await Promise.all(urlPromises);
  } catch (error) {
    console.error("Failed to get presigned URLs from COMS:", error);
    throw new Error(
      `Failed to get download URLs from COMS API. ${error instanceof Error ? error.message : "Please try again."}`,
    );
  }

  const totalSize = files.reduce((sum, f) => sum + f.size, 0);
  const totalSizeMB = totalSize / (1024 * 1024);

  //Create ZIP using zip.js
  await createZipWithZipJs(files, taskNumber, totalSizeMB);
}

/**
 * Create ZIP file using zip.js
 */
async function createZipWithZipJs(
  files: FileWithPresignedUrl[],
  taskNumber: number,
  totalSizeMB: number,
): Promise<void> {
  // Create ZIP writer
  const zipWriter = new zip.ZipWriter(new zip.BlobWriter("application/zip"), {
    bufferedWrite: true,
    useCompressionStream: true,
  });

  let completedFiles = 0;
  let failedFiles = 0;
  let totalBytesProcessed = 0;
  const failedFileNames: string[] = [];

  // Main processing loop
  for (let i = 0; i < files.length; i++) {
    const file = files[i];

    try {
      const result = await processSingleFile(file, zipWriter);
      completedFiles++;
      totalBytesProcessed += result.bytesProcessed;

      // Pause briefly between files to allow memory cleanup
      if (i + 1 < files.length) {
        await new Promise((resolve) => setTimeout(resolve, CONFIG.MEMORY_CLEANUP_DELAY_MS));
      }
    } catch (error) {
      failedFiles++;
      failedFileNames.push(file.name);

      console.error(`\nFAILED: ${file.name}`);
      console.error(`Final error: ${error instanceof Error ? error.message : String(error)}`);

      // Detailed error categorization
      if (error instanceof Error) {
        const { errorType } = categorizeError(error);
        console.error(`  → Type: ${errorType} ERROR`);
      }

      // Add error placeholder
      await addErrorPlaceholder(zipWriter, file, error, i, files.length);

      // Pause after error to allow memory recovery
      if (i + 1 < files.length) {
        await new Promise((resolve) => setTimeout(resolve, 3000));
      }
    }
  }

  // Summary
  showCompletionSummary(completedFiles, failedFiles, files.length, failedFileNames);

  // Finalize zip
  const zipBlob = await zipWriter.close();

  // Trigger download
  const downloadUrl = globalThis.URL.createObjectURL(zipBlob);
  const link = document.createElement("a");
  link.href = downloadUrl;
  link.download = `Task_${taskNumber}_Attachments.zip`;
  link.style.display = "none";

  document.body.appendChild(link);
  link.click();

  // Cleanup
  setTimeout(() => {
    link.remove();
    globalThis.URL.revokeObjectURL(downloadUrl);
  }, 1000);
}

// ==== HELPERS FUNCTIONS ====

function logMemory() {
  if ((performance as any).memory) {
    const mem = (performance as any).memory;
    const usedMB = (mem.usedJSHeapSize / 1024 / 1024).toFixed(0);
    const limitMB = (mem.jsHeapSizeLimit / 1024 / 1024).toFixed(0);
    const availableMB = ((mem.jsHeapSizeLimit - mem.usedJSHeapSize) / (1024 * 1024)).toFixed(0);
    const percentUsed = ((mem.usedJSHeapSize / mem.jsHeapSizeLimit) * 100).toFixed(1);

    if (Number.parseFloat(percentUsed) > CONFIG.MEMORY_HIGH_THRESHOLD) {
      console.warn(`Memory usage is HIGH (${percentUsed}%)`);
    }

    return {
      usedMB: Number.parseInt(usedMB),
      limitMB: Number.parseInt(limitMB),
      availableMB: Number.parseInt(availableMB),
      percentUsed: Number.parseFloat(percentUsed),
    };
  }
  return null;
}

async function downloadFileWithRetry(
  file: FileWithPresignedUrl,
): Promise<{ success: boolean; blob?: Blob; error?: Error; attempts: number }> {
  const result = await withRetry(
    async (attempt) => {
      const attemptPrefix = attempt > 1 ? `[Retry ${attempt - 1}/${CONFIG.MAX_RETRIES - 1}]` : "  ";

      // Check available memory before download
      if (attempt > 1) {
        const memInfo = logMemory();
        await checkMemoryBeforeDownload(memInfo, file, attemptPrefix);
      }

      // Download file
      const response = await fetch(file.url, { method: "GET" });

      if (!response.ok) {
        throw new Error(`HTTP ${response.status}: ${response.statusText}`);
      }

      const blob = await response.blob();
      validateBlobSize(blob, file, attemptPrefix);

      return blob;
    },
    {
      onRetry: (attempt, error) => {
        const { errorType } = categorizeError(error);
        console.error(`[Attempt ${attempt}/${CONFIG.MAX_RETRIES}] ✗ Failed: ${error.message} (${errorType})`);
      },
    },
  );

  if (result.success) {
    return { success: true, blob: result.result, attempts: result.attempts };
  }

  console.error(`All ${CONFIG.MAX_RETRIES} attempts failed for ${file.name}`);
  return { success: false, error: result.error, attempts: result.attempts };
}

function validateBlobSize(blob: Blob, file: FileWithPresignedUrl, attemptPrefix: string): void {
  if (blob.size === 0) {
    throw new Error("Downloaded blob is 0 bytes");
  }

  if (file.size > 0) {
    const sizeDiff = Math.abs(blob.size - file.size);
    const sizePercentDiff = (sizeDiff / file.size) * 100;

    if (sizePercentDiff > 5) {
      console.warn(
        `${attemptPrefix} Size mismatch: Expected ${(file.size / (1024 * 1024)).toFixed(2)}MB, ` +
          `got ${(blob.size / (1024 * 1024)).toFixed(2)}MB (${sizePercentDiff.toFixed(1)}% diff)`,
      );
    }
  }
}

async function checkMemoryBeforeDownload(
  memInfo: any,
  file: FileWithPresignedUrl,
  attemptPrefix: string,
): Promise<void> {
  if (!memInfo) return;
  const neededMB = (file.size / (1024 * 1024)) * 1.5;
  if (memInfo.availableMB < neededMB) {
    console.warn(`${attemptPrefix} Low memory detected. Waiting 3s for cleanup...`);
    await new Promise((resolve) => setTimeout(resolve, 3000));
  }
}

async function processSingleFile(
  file: FileWithPresignedUrl,
  zipWriter: any,
): Promise<{ success: boolean; bytesProcessed: number }> {
  // Download with retry
  const downloadResult = await downloadFileWithRetry(file);

  if (!downloadResult.success || !downloadResult.blob) {
    throw downloadResult.error || new Error("Download failed");
  }

  const blob = downloadResult.blob;

  // Add to ZIP
  const skipCompression =
    /\.(mp4|mov|avi|mkv|flv|wmv|webm|m4v|mpg|mpeg|3gp|zip|rar|7z|gz|bz2|xz|tar|jpg|jpeg|png|gif|webp|bmp|ico|svg|mp3|m4a|aac|ogg|flac|wav|wma|pdf|epub|mobi)$/i.test(
      file.name,
    );
  const compressionLevel = skipCompression ? 0 : 1;

  await zipWriter.add(file.name, new zip.BlobReader(blob), {
    level: compressionLevel,
    bufferedWrite: true,
  });

  return { success: true, bytesProcessed: blob.size };
}


async function addErrorPlaceholder(
  zipWriter: any,
  file: FileWithPresignedUrl,
  error: unknown,
  index: number,
  totalFiles: number,
): Promise<void> {
  try {
    const errorMessage =
      `Failed to download this file after ${CONFIG.MAX_RETRIES} attempts\n\n` +
      `Filename: ${file.name}\n` +
      `Expected Size: ${(file.size / (1024 * 1024)).toFixed(2)}MB\n` +
      `Error: ${error instanceof Error ? error.message : String(error)}\n` +
      `Error Type: ${error instanceof Error ? error.constructor.name : typeof error}\n` +
      `Timestamp: ${new Date().toISOString()}\n` +
      `File Index: ${index + 1} of ${totalFiles}\n` +
      `Retry Attempts: ${CONFIG.MAX_RETRIES}\n\n`;

    await zipWriter.add(`ERROR_${file.name}.txt`, new zip.TextReader(errorMessage), { level: 0 });
  } catch (placeholderError) {
    console.error(`Could not add error placeholder:`, placeholderError);
  }
}

function showCompletionSummary(
  completedFiles: number,
  failedFiles: number,
  totalFiles: number,
  failedFileNames: string[],
): void {
  if (failedFiles > 0) {
    console.log(`\n Failed files (after ${CONFIG.MAX_RETRIES} retry attempts each):`);
    failedFileNames.forEach((name, idx) => console.log(`    ${idx + 1}. ${name}`));

    ToggleWarning(
      `Downloaded ${completedFiles} of ${totalFiles} files. ` +
        `${failedFiles} failed after ${CONFIG.MAX_RETRIES} retry attempts.`,
      { autoClose: false },
    );
  } else {
    ToggleSuccess(`Successfully downloaded ${totalFiles} files.`, { autoClose: false });
  }
}
