import { createSlice } from "@reduxjs/toolkit";
import { RootState, AppThunk } from "../store";
import config from "../../../config";
import axios from "axios";
import { ComplaintState } from "../../types/state/complaint-state";
import { AllegationComplaint } from "../../types/complaints/allegation-complaint";
import { HwcrComplaint } from "../../types/complaints/hwcr-complaint";
import { ComplaintHeader } from "../../types/complaints/details/complaint-header";
import COMPLAINT_TYPES from "../../types/app/complaint-types";
import { ComplaintDetails } from "../../types/complaints/details/complaint-details";
import { ComplaintDetailsAttractant } from "../../types/complaints/details/complaint-attactant";

const initialState: ComplaintState = {
  complaints: [],
  complaint: null,
};

export const complaintSlice = createSlice({
  name: "allegationComplaints",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setComplaint: (state, action) => {
      const { payload: complaint } = action;

      return { ...state, complaint };
    },
  },

  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {},
});

// export the actions/reducers
export const { setComplaint } = complaintSlice.actions;

//--
export const getHwcrComplaintByComplaintIdentifier =
  (id: string): AppThunk =>
  async (dispatch) => {
    const token = localStorage.getItem("user");
    if (token) {
      axios.defaults.headers.common.Authorization = `Bearer ${token}`;

      const response = await axios.get(
        `${config.API_BASE_URL}/v1/hwcr-complaint/by-complaint-identifier/${id}`
      );
      const result = response.data;

      dispatch(setComplaint({ ...result }));
    }
  };

export const getErsComplaintByComplaintIdentifier =
  (id: string): AppThunk =>
  async (dispatch) => {
    const token = localStorage.getItem("user");
    if (token) {
      axios.defaults.headers.common.Authorization = `Bearer ${token}`;

      const response = await axios.get(
        `${config.API_BASE_URL}/v1/allegation-complaint/by-complaint-identifier/${id}`
      );
      const result = response.data;

      dispatch(setComplaint({ ...result }));
    }
  };

//-- selectors
export const selectComplaint = (
  state: RootState
): HwcrComplaint | AllegationComplaint | undefined | null => {
  const {
    complaints: { complaint },
  } = state;
  return complaint;
};

export const selectComplaintHeader =
  (complaintType: string) =>
  (state: RootState): any => {
    const selectHwcrComplaintHeader = (state: RootState): ComplaintHeader => {
      let result = {
        loggedDate: "",
        createdBy: "",
        lastUpdated: "",
        officerAssigned: "",
        status: "",
        natureOfComplaint: "", //-- needs to be violation as well
        species: "", //-- not available for ers
      };

      const { complaint } = state.complaints;

      if (complaint) {
        const {
          complaint_identifier: ceComplaint,
          hwcr_complaint_nature_code: ceComplaintNatureCode,
          species_code: ceSpeciesCode,
        } = complaint as HwcrComplaint;

        if (ceComplaint) {
          const officerAssigned = "Not Assigned";
          const {
            incident_reported_datetime: loggedDate,
            create_user_id: createdBy,
            update_timestamp: lastUpdated,
            complaint_status_code: ceStatusCode,
          } = ceComplaint;

          const { complaint_status_code: status } = ceStatusCode;

          result = {
            ...result,
            loggedDate,
            createdBy,
            lastUpdated,
            officerAssigned,
            status,
          };

          if (ceComplaintNatureCode) {
            const { long_description: natureOfComplaint } =
              ceComplaintNatureCode;
            result = { ...result, natureOfComplaint };
          }

          if (ceSpeciesCode) {
            const { short_description: species } = ceSpeciesCode;
            result = { ...result, species };
          }
        }
      }
      return result;
    };

    const selectErsComplaintHeader = (state: RootState): ComplaintHeader => {
      let result = {
        loggedDate: "",
        createdBy: "",
        lastUpdated: "",
        officerAssigned: "",
        status: "",
        violationType: "", //-- needs to be violation as well
      };

      const { complaint } = state.complaints;

      if (complaint) {
        const {
          complaint_identifier: ceComplaint,
          violation_code: ceViolation,
        } = complaint as AllegationComplaint;

        if (ceComplaint) {
          const officerAssigned = "Not Assigned";
          const {
            incident_reported_datetime: loggedDate,
            create_user_id: createdBy,
            update_timestamp: lastUpdated,
            complaint_status_code: ceStatusCode,
          } = ceComplaint;

          const { complaint_status_code: status } = ceStatusCode;

          result = {
            ...result,
            loggedDate,
            createdBy,
            lastUpdated,
            officerAssigned,
            status,
          };
        }

        if (ceViolation) {
          const { long_description: violationType } = ceViolation;
          result = { ...result, violationType };
        }
      }

      return result;
    };

    switch (complaintType) {
      case COMPLAINT_TYPES.ERS:
        return selectErsComplaintHeader(state);
      case COMPLAINT_TYPES.HWCR:
        return selectHwcrComplaintHeader(state);
    }
  };

export const selectComplaintDeails =
  (complaintType: string) =>
  (state: RootState): ComplaintDetails => {
    let results: ComplaintDetails = {};

    const { complaint } = state.complaints;

    if (complaint) {
      const { complaint_identifier: ceComplaint }: any = complaint;

      if (ceComplaint) {
        const {
          detail_text,
          location_summary_text,
          location_detailed_text,
          incident_datetime,
          location_geometry_point: { coordinates },
          cos_geo_org_unit: {
            area_name,
            region_name,
            zone_name,
            office_location_name,
          },
        } = ceComplaint;

        results = {
          ...results,
          details: detail_text,
          location: location_summary_text,
          locationDescription: location_detailed_text,
          incidentDateTime: incident_datetime,
          coordinates,
          area: area_name,
          region: region_name,
          zone: zone_name,
          office: office_location_name,
        };
      }
    }

    if(complaint){
      switch (complaintType) {
        case COMPLAINT_TYPES.ERS: {
          const {
            in_progress_ind: violationInProgress,
            observed_ind: violationObserved,
          }: any = complaint;
  
          results = { ...results, violationInProgress, violationObserved };
          break;
        }
        case COMPLAINT_TYPES.HWCR: {
          const { attractant_hwcr_xref }: any = complaint;
  
          const attractants = attractant_hwcr_xref.map(
            ({
              attractant_hwcr_xref_guid: key,
              attractant_code: { short_description: description },
            }: any): ComplaintDetailsAttractant => {
              return { key, description };
            }
          );
  
          results = { ...results, attractants };
          break;
        }
      }
    }

    return results;
  };
export default complaintSlice.reducer;
