--
-- Deprecated: This script was originally developed when first onboarding CEEB and should have been 
-- created as a versioned script.  
--
-- The previous behavior of the script was to:
--    - Set the complaint owner to CEEB of all Waste and Pesticide complaints
--    - Set the complaint owner to COS for all other complaints that do not have a complaint owner
--
-- Now that referrals have been added to the system, these actions will cause data corruption.
