ALTER TABLE attractant_hwcr_xref ADD CONSTRAINT UQ_attrhwcrx UNIQUE (attractant_code, hwcr_complaint_guid);

comment on column allegation_complaint.complaint_identifier is 'Natural key for a complaint generated by webEOC.';