export const CASE_ACTION_TYPE = {
    ASSESESSMENT: "COMPASSESS",
    PREVENTION_EDUCATION: "COSPRV&EDU",
    EQUIPMENT: "EQUIPMENT",
}

export const CASE_ACTION_CODE = {
    ASSESSRISK: "ASSESSRISK",
    ASSESSHLTH: "ASSESSHLTH",
    ASSESSHIST: "ASSESSHIST",
    CNFRMIDENT: "CNFRMIDENT",
    PROVSFTYIN: "PROVSFTYIN",
    PROVAMHSIN: "PROVAMHSIN",
    CDCTMEDREL: "CDCTMEDREL",
    SETEQUIPMT: "SETEQUIPMT",
    REMEQUIPMT: "REMEQUIPMT",
    CNTCTBYLAW: "CNTCTBYLAW",
    CNTCTGROUP: "CNTCTGROUP",
    CNTCTBIOVT: "CNTCTBIOVT",
    DIRLOWLACT: "DIRLOWLACT",
    CONTACTLPP: "CONTACTLPP",
    UPDATENOTE: "UPDATENOTE",
}