export const CODE_TABLE_TYPES = {
  AGENCY: "agency",
  ATTRACTANT: "attractant",
  COMPLAINT_STATUS: "complaint-status",
  COMPLAINT_TYPE: "complaint-type",
  NATURE_OF_COMPLAINT: "nature-of-complaint",
  SPECIES: "species",
  VIOLATIONS: "violation",
  REGIONS: "regions",
  ZONES: "zones",
  COMMUNITIES: "communities",
  AREA_CODES: "area-codes",
  REPORTED_BY: "reported-by",
  JUSTIFICATION: "justification",
  ASSESSMENT_TYPE: "assessment-type",
  PREVENTION_TYPE: "prevention-type",
  SEX: "sex",
  AGE: "age",
  THREAT_LEVEL: "threat-level",
  CONFLICT_HISTORY: "conflict-history",
  EARS: "ear-tag",
  WILDLIFE_OUTCOMES: "wildlife-outcomes",
  HWCR_OUTCOME_ACTIONED_BY: "hwcr-outcome-actioned-by-codes",
  DRUGS: "drugs",
  DRUG_METHOD_USE: "drug-methods",
  REMAINING_DRUG_USE: "drug-remaining-outcomes",
  EQUIPMENT: "equipment",
  GIR_TYPE: "gir-type",
  DISCHARGE: "discharge",
  NON_COMPLIANCE: "non-compliance",
  SECTOR: "sector",
  SCHEDULE: "schedule",
  DECISION_TYPE: "decision-type",
  TEAM: "team",
  COMPLAINT_METHOD_RECEIVED: "complaint-method-received-codes",
  LEAD_AGENCY: "lead-agency",
  SCHEDULE_SECTOR: "schedule-sector",
  SCHEDULE_SECTOR_TYPE: "schedule-sector-type",
  ASSESSMENT_CAT1_TYPE: "assessment-cat1-type",
  IPM_AUTH_CATEGORY_TYPE: "ipm-auth-category",
  CASE_LOCATION_TYPE: "case-location-type",
  EQUIPMENT_STATUS: "equipment-status",
  PARK_AREA: "park-area",
  EMAIL_REFERENCE: "email-reference",
  PARTY_TYPE: "party-type",
  PARTY_ASSOCIATION_ROLE: "party-association-role",

  //  ORGANIZATION_UNIT_TYPE: "organization-unit-type",
  //  ORGANIZATION_UNIT: "organization-unit",
  //  PERSON_TYPE: "person-complaint",
};
