INSERT INTO shared.species_code
    (species_code, short_description, long_description, display_order, large_carnivore_ind, display_on_complaint_ind, create_user_id, active_ind)

VALUES
    ('BLKBEAR', 'Bear, Black', 'Bear, Black', 10, true, true, 'postgres', true),
    ('GRZBEAR', 'Bear, Grizzly', 'Bear, Grizzly', 20, true, true, 'postgres', true),
    ('KRMBEAR', 'Bear, Kermode', 'Bear, Kermode', 30, true, false, 'postgres', true),
    ('BEAVER', 'Beaver', 'Beaver', 40, false, false, 'postgres', true),
    ('BISON', 'Bison', 'Bison', 50, false, true, 'postgres', true),
    ('BOBCAT', 'Bobcat', 'Bobcat', 60, false, true, 'postgres', true),
    ('CARIBOU', 'Caribou', 'Caribou', 70, false, true, 'postgres', true),
    ('CATTLE', 'Cattle', 'Cattle', 80, false, false, 'postgres', true),
    ('COUGAR', 'Cougar', 'Cougar', 90, true, true, 'postgres', true),
    ('COYOTE', 'Coyote', 'Coyote', 100, true, true, 'postgres', true),
    ('CRWRVN', 'Crow/Raven', 'Crow/Raven', 110, true, false, 'postgres', true),
    ('DEER', 'Deer, (General)', 'Deer, (General)', 120, false, true, 'postgres', true),
    ('DEERBT', 'Deer, Black-Tailed', 'Deer, Black-Tailed', 130, false, false, 'postgres', true),
    ('DEERMU', 'Deer, Mule', 'Deer, Mule', 140, false, false, 'postgres', true),
    ('DEERWT', 'Deer, White-Tailed', 'Deer, White-Tailed', 150, false, false, 'postgres', true),
    ('DUCK', 'Duck, (General)', 'Duck, (General)', 160, false, false, 'postgres', true),
    ('EAGLE', 'Eagle, (General)', 'Eagle, (General)', 170, false, false, 'postgres', true),
    ('ELK', 'Elk, (General)', 'Elk, (General)', 180, false, true, 'postgres', true),
    ('ELKRM', 'Elk, Rocky Mountain', 'Elk, Rocky Mountain', 190, false, false, 'postgres', true),
    ('ELKRV', 'Elk, Roosevelt', 'Elk, Roosevelt', 200, false, false, 'postgres', true),
    ('FISH', 'Fish, (General)', 'Fish, (General)', 210, false, false, 'postgres', true),
    ('FOX', 'Fox', 'Fox', 220, false, true, 'postgres', true),
    ('GAMEBIRD', 'Game Bird, (Other)', 'Game Bird, (Other)', 230, false, false, 'postgres', true),
    ('GOOSEGEN', 'Goose, (General)', 'Goose, (General)', 240, false, false, 'postgres', true),
    ('GOOSECAN', 'Goose, Canada', 'Goose, Canada', 250, false, false, 'postgres', true),
    ('GROUSE', 'Grouse, (General)', 'Grouse, (General)', 260, false, false, 'postgres', true),
    ('GULL', 'Gull, (General)', 'Gull, (General)', 270, false, false, 'postgres', true),
    ('HALIBUT', 'Halibut', 'Halibut', 280, false, false, 'postgres', true),
    ('KOKANEE', 'Kokanee', 'Kokanee', 290, false, false, 'postgres', true),
    ('FERALHOG', 'Hog/Pig/Boar (Feral)', 'Hog/Pig/Boar (Feral)', 300, false, true, 'postgres', true),
    ('LYNX', 'Lynx', 'Lynx', 310, false, true, 'postgres', true),
    ('MARMOT', 'Marmot, (General)', 'Marmot, (General)', 320, false, false, 'postgres', true),
    ('MIGBIRD', 'Migratory Bird, (Other)', 'Migratory Bird, (Other)', 330, false, false, 'postgres', true),
    ('MOOSE', 'Moose', 'Moose', 340, false, true, 'postgres', true),
    ('MTNGOAT', 'Mountain Goat', 'Mountain Goat', 350, false, true, 'postgres', true),
    ('OTHER', 'Other', 'Other', 360, false, true, 'postgres', true),
    ('RACCOON', 'Raccoon', 'Raccoon', 370, false, true, 'postgres', true),
    ('RAPTOR', 'Raptor', 'Raptor', 380, false, true, 'postgres', true),
    ('RATTLER', 'Rattlesnake', 'Rattlesnake', 390, false, true, 'postgres', true),
    ('RVROTTER', 'River Otter', 'River Otter', 400, false, true, 'postgres', true),
    ('SALMON', 'Salmon, (General)', 'Salmon, (General)', 410, false, false, 'postgres', true),
    ('WLDSHEEP', 'Sheep, (General)', 'Sheep, (General)', 420, false, true, 'postgres', true),
    ('CBHSHEEP', 'Sheep, California Big Horn', 'Sheep, California Big Horn', 430, false, false, 'postgres', true),
    ('DLLSHEEP', 'Sheep, Dall', 'Sheep, Dall', 440, false, false, 'postgres', true),
    ('RBHSHEEP', 'Sheep, Rocky Mountain Big Horn', 'Sheep, Rocky Mountain Big Horn', 450, false, false, 'postgres', true),
    ('STNSHEEP', 'Sheep, Stone', 'Sheep, Stone', 460, false, false, 'postgres', true),
    ('SHLFISH', 'Shellfish, (General)', 'Shellfish, (General)', 470, false, false, 'postgres', true),
    ('SHRBIRD', 'Shorebirds, (General)', 'Shorebirds, (General)', 480, false, false, 'postgres', true),
    ('SKUNK', 'Skunk', 'Skunk', 490, false, true, 'postgres', true),
    ('SMLBIRD', 'Small Birds, (General)', 'Small Birds, (General)', 500, false, false, 'postgres', true),
    ('SNAKE', 'Snake, (General)', 'Snake, (General)', 510, false, false, 'postgres', true),
    ('SQUIRREL', 'Squirrel, (General)', 'Squirrel, (General)', 520, false, false, 'postgres', true),
    ('STEELHEAD', 'Steelhead', 'Steelhead', 530, false, false, 'postgres', true),
    ('STURGEON', 'Sturgeon, (General)', 'Sturgeon, (General)', 540, false, false, 'postgres', true),
    ('TROUT', 'Trout, (General)', 'Trout, (General)', 550, false, false, 'postgres', true),
    ('TURKEY', 'Turkey, (General)', 'Turkey, (General)', 560, false, false, 'postgres', true),
    ('TURTLE', 'Turtle, (General)', 'Turtle, (General)', 570, false, false, 'postgres', true),
    ('UNKNOWN', 'Unknown', 'Unknown', 580, false, true, 'postgres', true),
    ('WATERFOWL', 'Waterfowl (General)', 'Waterfowl (General)', 590, false, false, 'postgres', true),
    ('WOLF', 'Wolf', 'Wolf', 600, true, true, 'postgres', true),
    ('WOLVERN', 'Wolverine', 'Wolverine', 610, false, true, 'postgres', true),
    ('CASMAMMAL', 'Control Alien Species, Mammal', 'Control Alien Species, Mammal', 620, false, false, 'postgres', true),
    ('CASREPTILE', 'Control Alien Species, Reptile', 'Control Alien Species, Reptile', 630, false, false, 'postgres', true),
    ('CASOTHER', 'Control Alien Species, Other', 'Control Alien Species, Other', 640, false, false, 'postgres', true),
    ('INVFISH', 'Invasive Species, Fish', 'Invasive Species, Fish', 650, false, false, 'postgres', true),
    ('INVMUSSEL', 'Invasive Species, Mussel - Zebra, Quagga, Golden', 'Invasive Species, Mussel - Zebra, Quagga, Golden', 660, false, false, 'postgres', true),
    ('INVOTHER', 'Invasive Species, Other', 'Invasive Species, Other', 670, false, false, 'postgres', true)
  ON CONFLICT (species_code) DO UPDATE SET
      short_description = EXCLUDED.short_description,
      long_description = EXCLUDED.long_description,
      display_order = EXCLUDED.display_order,
      active_ind = EXCLUDED.active_ind,
      large_carnivore_ind = EXCLUDED.large_carnivore_ind,
      display_on_complaint_ind = EXCLUDED.display_on_complaint_ind,
      update_user_id = 'FLYWAY',
      update_utc_timestamp = now();

