import { ApiProperty } from "@nestjs/swagger";
import { UUID } from "crypto";
import { Complaint } from "../../complaint/entities/complaint.entity";
import { SpeciesCode } from "src/v1/species_code/entities/species_code.entity";
import { HwcrComplaintNatureCode } from "src/v1/hwcr_complaint_nature_code/entities/hwcr_complaint_nature_code.entity";
import { AttractantHwcrXref } from "src/v1/attractant_hwcr_xref/entities/attractant_hwcr_xref.entity";

export class HwcrComplaintDto
{
  @ApiProperty({
    example: "903f87c8-76dd-427c-a1bb-4d179e443252",
    description: "System generated unique key for a hwcr complaint. This key should never be exposed to users via any system utilizing the tables.",
  })
  hwcr_complaint_guid: UUID;

  @ApiProperty({ example: "COS-5436", description: "Natural key for a complaint generated by webEOC." })
  complaint_identifier: Complaint;

  @ApiProperty({ example: "BOBCAT", description: "A human readable code used to identify a wildlife species." })
  species_code: SpeciesCode;

  @ApiProperty({ example: "HUMINJ", description: "A human readable code used to identify the nature of the Human Wildlife Conflict." })
  hwcr_complaint_nature_code: HwcrComplaintNatureCode;

  attractant_hwcr_xref: AttractantHwcrXref[];

  @ApiProperty({
    example: "Witnessed individual dumping garbage on crown land",
    description: "Provides a more detailed description when the attractant of type \"OTHER\" is included."
  })
  other_attractants_text: string;

  @ApiProperty({
    example: "IDIR\mburns",
    description: "The id of the user that created the HWCR complaint.",
  })
  create_user_id: string;

  @ApiProperty({
    example: "903f87c8-76dd-427c-a1bb-4d179e443252",
    description: "The unique guid of the user that created the HWCR complaint.",
  })
  create_user_guid: UUID;

  @ApiProperty({
    example: "2003-04-12 04:05:06",
    description: "The timestamp when the HWCR complaint was created.  The timestamp is stored in UTC with no Offset.",
  })
  create_timestamp: Date;

  @ApiProperty({
    example: "IDIR\mburns",
    description: "The id of the user that updated the HWCR complaint.",
  })
  update_user_id: string;

  @ApiProperty({
    example: "903f87c8-76dd-427c-a1bb-4d179e443252",
    description: "The unique guid of the user that updated the HWCR complaint.",
  })
  update_user_guid: UUID;

  @ApiProperty({
    example: "2003-04-12 04:05:06",
    description: "The timestamp when the HWCR complaint was updated.  The timestamp is stored in UTC with no Offset.",
  })
  update_timestamp: Date;
}
