---
kind: RunbookParser
metadata:
  name: n8n-parser
  labels:
    owner: Compliance and Enforcement
spec:
  root: tools/n8n/
  destination: tools/n8n/snippets/
  working_dir: /tmp
  sources:
    # using the same name will combine snippets in the same destination to produce more composable workflows in the same domain, eg crunchy+postgres
    - name: crunchy-triage
      description: A set of snippets used to fetch and collect triage information from a crunchy db cluster in a given openshift namespace.
      # if a doc file is specified, all snippets (code+documentation) are recombined so that diffs between snippets vs docs can be detected
      # src -> snippets -> doc, if src is 1 document that src == doc
      doc: null
      # if the doc last changed is older than source last changed then check for a diff
      doc_last_updated: null
      # wiki/doc/runbook to pull from
      url: https://github.com/bcgov/wps/blob/main/docs/database/CLUSTER_DB.MD
      # direct filepath in local codebase to pull from
      file: null
      # timestamp the last time the source was editted.
      source_last_updated: null
    - name: crunchy-triage
      description: A set of snippets used to fetch and collect triage information from a crunchy db cluster in a given openshift namespace.
      doc: crunchy-disaster-recovery.md
      doc_last_updated: null
      url: https://github.com/bcgov/nr-compliance-enforcement/wiki/Disaster-Recovery
      file: null
      source_last_updated: null
    - name: crunchy-triage
      description: A set of bash snippets that use psql to query key information about a postgres instance. Namely current vs max connections, memory usage, WAL details, long running queries, slow queries. Postgres version 17.
      doc: null
      doc_last_updated: null
      url: null
      file: null
      source_last_updated: null
  runbooks:
    - name: crunchy-triage
      last_updated: null
      snippets_from:
        - crunchy-triage
