type Mutation {
  addPartyToInvestigation(investigationGuid: String!, input: [CreateInvestigationPartyInput]!): [InvestigationParty!]!
  addPartyToInvestigationFromSharedParty(
    investigationGuid: String!
    partyReference: String!
    partyAssociationRole: String!
    attachmentReferences: [CreateAttachmentReferenceInput]
  ): InvestigationParty!
  removePartyFromInvestigation(investigationGuid: String!, partyIdentifier: String!): Investigation!
  editPartyRoleInInvestigation(
    investigationGuid: String!
    partyIdentifier: String!
    partyAssociationRole: String!
  ): Investigation!
  updateInvestigationParty(investigationGuid: String!, input: UpdateInvestigationPartyInput!): Investigation!
  updateInvestigationPartyFromSharedParty(
    investigationGuid: String!
    partyIdentifier: String!
    attachmentReferences: [CreateAttachmentReferenceInput]
  ): Investigation!
  replacePartyOnInvestigation(
    investigationGuid: String!
    partyIdentifier: String!
    input: CreateInvestigationPartyInput!
  ): InvestigationParty!
  replacePartyOnInvestigationFromSharedParty(
    investigationGuid: String!
    partyIdentifier: String!
    partyReference: String!
    partyAssociationRole: String!
    attachmentReferences: [CreateAttachmentReferenceInput]
  ): InvestigationParty!
}

type Query {
  InvestigationParties(partyRefId: String!): [InvestigationParty]!
}
