type EnforcementAction {
  enforcementActionIdentifier: String!
  contraventionPartyXrefIdentifier: String!
  enforcementActionCode: EnforcementActionCode!
  dateIssued: DateTime!
  geoOrganizationUnitCode: String!
  appUserIdentifier: String!
  activeIndicator: Boolean!
  ticket: Ticket
  comment: String
  publishedPartyReference: String
  issuingOfficerIdentifier: String
  dateServed: DateTime
  warningNumber: String
  sanctionTypeCode: String
  effectiveDate: DateTime
  endDate: DateTime
  sanctionStatusCode: String
  orderTypeCode: String
  remediationRequired: Boolean
  appealHearingDate: DateTime
  orderStatusCode: String
  hearingDate: DateTime
  decisionDate: DateTime
  courtProsecutionStatusCode: String
  administrativePenaltyStatusCode: String
  approvalInd: Boolean
}

input CreateEnforcementActionInput {
  contraventionIdentifier: String!
  partyIdentifier: String
  enforcementActionCode: String!
  dateIssued: DateTime!
  geoOrganizationUnitCode: String!
  appUserIdentifier: String!
  ticketOutcomeCode: String
  ticketAmount: Float
  ticketNumber: String
  paidDate: DateTime
  comment: String
  issuingOfficerIdentifier: String
  dateServed: DateTime
  ticketTypeCode: String
  warningNumber: String
  sanctionTypeCode: String
  effectiveDate: DateTime
  endDate: DateTime
  sanctionStatusCode: String
  orderTypeCode: String
  remediationRequired: Boolean
  appealHearingDate: DateTime
  orderStatusCode: String
  hearingDate: DateTime
  decisionDate: DateTime
  courtProsecutionStatusCode: String
  administrativePenaltyStatusCode: String
  approvalInd: Boolean
}

input UpdateEnforcementActionInput {
  enforcementActionIdentifier: String!
  enforcementActionCode: String
  dateIssued: DateTime
  geoOrganizationUnitCode: String
  appUserIdentifier: String
  ticketOutcomeCode: String
  ticketAmount: Float
  ticketNumber: String
  paidDate: DateTime
  comment: String
  issuingOfficerIdentifier: String
  dateServed: DateTime
  ticketTypeCode: String
  warningNumber: String
  sanctionTypeCode: String
  effectiveDate: DateTime
  endDate: DateTime
  sanctionStatusCode: String
  orderTypeCode: String
  remediationRequired: Boolean
  appealHearingDate: DateTime
  orderStatusCode: String
  hearingDate: DateTime
  decisionDate: DateTime
  courtProsecutionStatusCode: String
  administrativePenaltyStatusCode: String
  approvalInd: Boolean
}
