{{- if and .Values.global.secrets .Values.global.secrets.enabled }}
{{- $databaseUser := .Values.global.secrets.databaseUser | default "postgres" }}
{{- $databasePassword := .Values.global.secrets.databasePassword | default (randAlphaNum 10) }}
{{- $caseManagementApiKey := .Values.global.secrets.caseManagementApiKey | default (randAlphaNum 10) }}
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "nr-compliance-enforcement") | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}

# Set databasePassword to existing secret data or generate a random one when not exists
{{- $databasePassword = (get $secretData "databasePassword" | default ($databasePassword | b64enc)) }}
{{- $databaseName := .Values.global.secrets.databaseName | default "postgres" }}
{{- $host := printf "%s-%s:5432" .Release.Name .Values.global.databaseAlias }}
{{- $hostWithoutPort := printf "%s-%s" .Release.Name .Values.global.databaseAlias }}
{{- $databaseURL := printf "postgresql://%s:%s@%s/%s" $databaseUser (b64dec $databasePassword) $host $databaseName }}
{{- $databaseJDBCURL := printf "jdbc:postgresql://%s:%s@%s/%s" $databaseUser (b64dec $databasePassword) $host $databaseName }}
{{- $databaseJDBCURLNoCreds := printf "jdbc:postgresql://%s/%s" $host $databaseName }}

{{- $bcGeocoderApiClientId := (get $secretData "bcGeocoderApiClientId" | b64dec | default (randAlphaNum 10)) }}
{{- $bcGeocoderApiKey := (get $secretData "bcGeocoderApiKey" | b64dec | default (randAlphaNum 10)) }}
{{- $bcGeocoderApiUrl := (get $secretData "bcGeocoderApiUrl" | b64dec | default "") }}
{{- $comsJwtAuthUri := (get $secretData "comsJwtAuthUri" | b64dec | default "") }}
{{- $cdogsUri := (get $secretData "cdogsUri" | b64dec | default "") }}
{{- $cdogsClientId := (get $secretData "cdogsClientId" | b64dec | default "") }}
{{- $cdogsClientSecret := (get $secretData "cdogsClientSecret" | b64dec | default "") }}
{{- $cssUrl := (get $secretData "cssUrl" | b64dec | default "") }}
{{- $cssTokenUrl := (get $secretData "cssTokenUrl" | b64dec | default "") }}
{{- $cssClientId := (get $secretData "cssClientId" | b64dec | default "") }}
{{- $cssClientSecret := (get $secretData "cssClientSecret" | b64dec | default "") }}
{{- $environment := (get $secretData "environment" | b64dec | default "") }}
{{- $comsUrl := (get $secretData "comsUrl" | b64dec | default "") }}
{{- $comsAccessKeyId := (get $secretData "comsAccessKeyId" | b64dec | default "") }}
{{- $comsBucket := (get $secretData "comsBucket" | b64dec | default "") }}
{{- $comsBucketName := (get $secretData "comsBucketName" | b64dec | default "") }}
{{- $comsKey := (get $secretData "comsKey" | b64dec | default "") }}
{{- $comsEndpoint := (get $secretData "comsEndpoint" | b64dec | default "") }}
{{- $comsSecretKey := (get $secretData "comsSecretKey" | b64dec | default "") }}
{{- $webeocUsername := (get $secretData "webeocUsername" | b64dec | default "") }}
{{- $webeocPassword := (get $secretData "webeocPassword" | b64dec | default "") }}
{{- $webeocPosition := (get $secretData "webeocPosition" | b64dec | default "") }}
{{- $webeocIncident := (get $secretData "webeocIncident" | b64dec | default "") }}
{{- $webeocUrl := (get $secretData "webeocUrl" | b64dec | default "") }}
{{- $webeocComplaintHistorySeconds := (get $secretData "webeocComplaintHistorySeconds" | b64dec | default "") }}
{{- $webeocCronExpression := (get $secretData "webeocCronExpression" | b64dec | default "") }}
{{- $backupDir := (get $secretData "backupDir" | b64dec | default "") }}
{{- $backupStrategy := (get $secretData "backupStrategy" | b64dec | default "") }}
{{- $numBackups := (get $secretData "numBackups" | b64dec | default "") }}
{{- $dailyBackups := (get $secretData "dailyBackups" | b64dec | default "") }}
{{- $weeklyBackups := (get $secretData "weeklyBackups" | b64dec | default "") }}
{{- $monthlyBackups := (get $secretData "monthlyBackups" | b64dec | default "") }}
{{- $databaseServiceName := (get $secretData "databaseServiceName" | b64dec | default "") }}
{{- $objectstoreAccessKey := (get $secretData "objectstoreAccessKey" | b64dec | default "") }}
{{- $objectstoreUrl := (get $secretData "objectstoreUrl" | b64dec | default "") }}
{{- $objectstoreHttpsUrl := (get $secretData "objectstoreHttpsUrl" | b64dec | default "") }}
{{- $objectstoreBackupDirectory := (get $secretData "objectstoreBackupDirectory" | b64dec | default "") }}
{{- $objectstoreBucket := (get $secretData "objectstoreBucket" | b64dec | default "") }}
{{- $objectstoreSecretKey := (get $secretData "objectstoreSecretKey" | b64dec | default "") }}
{{- $jwksUri := (get $secretData "jwksUri" | b64dec | default "") }}
{{- $jwtIssuer := (get $secretData "jwtIssuer" | b64dec | default "") }}
{{- $keycloakClientId := (get $secretData "keycloakClientId" | b64dec | default "") }}
{{- $caseManagementApiUrl := (get $secretData "caseManagementApiUrl" | b64dec | default "") }}


{{- if not (lookup "v1" "Secret" .Release.Namespace (printf "%s-backend" .Release.Name)) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend
  labels: {{- include "labels" . | nindent 4 }}
  {{- if .Values.global.secrets.persist }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
data:
  # BACKEND Secrets
  POSTGRESQL_PASSWORD: {{ $databasePassword | quote }}
  POSTGRESQL_USER: {{ $databaseUser | b64enc | quote }}
  POSTGRESQL_DATABASE: {{ $databaseName | b64enc | quote }}
  POSTGRESQL_HOST: {{ $hostWithoutPort | b64enc | quote }}
  JWKS_URI: {{ $jwksUri | b64enc | quote }}
  JWT_ISSUER: {{ $jwtIssuer | b64enc | quote }}
  KEYCLOCK_CLIENT_ID: {{ $keycloakClientId | b64enc | quote }}
  BC_GEOCODER_API_CLIENT_ID: {{ $bcGeocoderApiClientId | b64enc | quote }}
  BC_GEOCODER_API_KEY: {{ $bcGeocoderApiKey | b64enc | quote }}
  BC_GEOCODER_API_URL: {{ $bcGeocoderApiUrl | b64enc | quote }}
  CASE_MANAGEMENT_API_URL: {{ $caseManagementApiUrl | b64enc | quote }}
  COMPLAINTS_API_KEY: {{ $caseManagementApiKey | b64enc | quote }}
  POSTGRESQL_ENABLE_LOGGING: {{ .Values.global.secrets.postgresqlEnableLogging | b64enc }}
  COMS_JWT_AUTH_URI: {{ $comsJwtAuthUri | b64enc | quote }}
  CDOGS_URI: {{ $cdogsUri | b64enc | quote }}
  CDOGS_CLIENT_ID: {{ $cdogsClientId | b64enc | quote }}
  CDOGS_CLIENT_SECRET: {{ $cdogsClientSecret | b64enc | quote }}
  CSS_URL: {{ $cssUrl | b64enc | quote }}
  CSS_TOKEN_URL: {{ $cssTokenUrl | b64enc | quote }}
  CSS_CLIENT_ID: {{ $cssClientId | b64enc | quote }}
  CSS_CLIENT_SECRET: {{ $cssClientSecret | b64enc | quote }}
  ENVIRONMENT: {{ $environment | b64enc | quote }}
  # COMS Secrets
  COMS_URL: {{ $comsUrl | b64enc | quote }}
  COMS_ACCESS_KEY_ID: {{ $comsAccessKeyId | b64enc | quote }}
  COMS_BUCKET: {{ $comsBucket | b64enc | quote }}
  COMS_BUCKET_NAME: {{ $comsBucketName | b64enc | quote }}
  COMS_KEY: {{ $comsKey | b64enc | quote }}
  COMS_ENDPOINT: {{ $comsEndpoint | b64enc | quote }}
  COMS_SECRET_KEY: {{ $comsSecretKey | b64enc | quote }}
  # BACKUP Secrets
  BACKUP_DIR: {{ $backupDir | b64enc | quote }}
  BACKUP_STRATEGY: {{ $backupStrategy | b64enc | quote }}
  NUM_BACKUPS: {{ $numBackups | b64enc | quote }}
  DAILY_BACKUPS: {{ $dailyBackups | b64enc | quote }}
  WEEKLY_BACKUPS: {{ $weeklyBackups | b64enc | quote }}
  MONTHLY_BACKUPS: {{ $monthlyBackups | b64enc | quote }}
  DATABASE_SERVICE_NAME: {{ $databaseServiceName | b64enc | quote }}
  OBJECTSTORE_ACCESS_KEY: {{ $objectstoreAccessKey | b64enc | quote }}
  OBJECTSTORE_URL: {{ $objectstoreUrl | b64enc | quote }}
  OBJECTSTORE_HTTPS_URL: {{ $objectstoreHttpsUrl | b64enc | quote }}
  OBJECTSTORE_BACKUP_DIRECTORY: {{ $objectstoreBackupDirectory | b64enc | quote }}
  OBJECTSTORE_BUCKET: {{ $objectstoreBucket | b64enc | quote }}
  OBJECTSTORE_SECRET_KEY: {{ $objectstoreSecretKey | b64enc | quote }}
{{- end }}
{{- if not (lookup "v1" "Secret" .Release.Namespace (printf "%s-webeoc" .Release.Name)) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-webeoc
  labels: {{- include "labels" . | nindent 4 }}
  {{- if .Values.global.secrets.persist }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
data:
  # WEBEOC Secrets
  WEBEOC_USERNAME: {{ $webeocUsername | b64enc | quote }}
  WEBEOC_PASSWORD: {{ $webeocPassword | b64enc | quote }}
  WEBEOC_POSITION: {{ $webeocPosition | b64enc | quote }}
  WEBEOC_INCIDENT: {{ $webeocIncident | b64enc | quote }}
  WEBEOC_URL: {{ $webeocUrl | b64enc | quote }}
  WEBEOC_COMPLAINT_HISTORY_SECONDS: {{ $webeocComplaintHistorySeconds | b64enc | quote }}
  WEBEOC_CRON_EXPRESSION: {{ $webeocCronExpression | b64enc | quote }}
  COMPLAINTS_API_KEY: {{ $caseManagementApiKey | b64enc | quote }}
{{- end }}
{{- if not (lookup "v1" "Secret" .Release.Namespace (printf "%s-flyway" .Release.Name)) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-flyway
  labels: {{- include "labels" . | nindent 4 }}
  {{- if .Values.global.secrets.persist }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
data:
  FLYWAY_URL: {{ $databaseJDBCURLNoCreds | b64enc | quote }}
  FLYWAY_USER: {{ $databaseUser | b64enc | quote }}
  FLYWAY_PASSWORD: {{ $databasePassword | quote }}
{{- end }}
{{- if not (lookup "v1" "Secret" .Release.Namespace (printf "%s-database" .Release.Name)) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-database
  labels: {{- include "labels" . | nindent 4 }}
  {{- if .Values.global.secrets.persist }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
data:
  postgres-password: {{ $databasePassword  | quote }}
  password: {{ $databasePassword | quote }}
{{- end }}

{{- end }}
