{{- if and .Values.global.secrets .Values.global.secrets.enabled}}
{{- $databaseUser := .Values.global.secrets.databaseUser| default "postgres"  }}
{{- $databasePassword := .Values.global.secrets.databasePassword | default (randAlphaNum 10) }}
{{- $caseManagementApiKey := .Values.global.secrets.caseManagementApiKey | default (randAlphaNum 10) }}
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace  .Release.Name ) | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}
  # set below to existing secret data or generate a random one when not exists
{{- $databasePassword = (get $secretData "databasePassword") | default ($databasePassword | b64enc) }}
{{- $databaseName := .Values.global.secrets.databaseName| default "postgres" }}
{{- $host := printf "%s-%s:5432" .Release.Name .Values.global.databaseAlias }}
{{- $hostWithoutPort := printf "%s-%s" .Release.Name .Values.global.databaseAlias }}
{{- $databaseURL := printf "postgresql://%s:%s@%s/%s" $databaseUser (b64dec $databasePassword) $host $databaseName }}
{{- $databaseJDBCURL := printf "jdbc:postgresql://%s:%s@%s/%s" $databaseUser (b64dec $databasePassword) $host $databaseName }}
{{- $databaseJDBCURLNoCreds := printf "jdbc:postgresql://%s/%s" $host $databaseName }}

{{- $jwksUri := printf "%s-%s:5432" .Release.Name .Values.global.jwksUri }}
{{- $jwtIssuer := printf "%s-%s:5432" .Release.Name .Values.global.jwtIssuer }}
{{- $keycloakClientId := printf "%s-%s:5432" .Release.Name .Values.global.keycloakClientId }}
{{- $bcGeocoderApiClientId := printf "%s-%s:5432" .Release.Name .Values.global.bcGeocoderApiClientId }}
{{- $bcGeocoderApiKey := printf "%s-%s:5432" .Release.Name .Values.global.secrets.bcGeocoderApiKey }}
{{- $bcGeocoderApiUrl := printf "%s-%s:5432" .Release.Name .Values.global.secrets.bcGeocoderApiUrl }}
{{- $caseManagementApiUrl := printf "%s-%s:5432" .Release.Name .Values.global.secrets.caseManagementApiUrl }}
{{- $postgresqlEnableLogging := printf "%s-%s:5432" .Release.Name .Values.global.secrets.postgresqlEnableLogging }}
{{- $comsJwtAuthUri := printf "%s-%s:5432" .Release.Name .Values.global.secrets.comsJwtAuthUri }}
{{- $cdogsUri := printf "%s-%s:5432" .Release.Name .Values.global.secrets.cdogsUri }}
{{- $cdogsClientId := printf "%s-%s:5432" .Release.Name .Values.global.secrets.cdogsClientId }}
{{- $cdogsClientSecret := printf "%s-%s:5432" .Release.Name .Values.global.cdogsClientSecret }}
{{- $webeocUsername := printf "%s-%s:5432" .Release.Name .Values.global.secrets.webeocUsername }}
{{- $webeocPassword := printf "%s-%s:5432" .Release.Name .Values.global.secrets.webeocPassword }}
{{- $webeocPosition := printf "%s-%s:5432" .Release.Name .Values.global.secrets.webeocPosition }}
{{- $webeocIncident := printf "%s-%s:5432" .Release.Name .Values.global.secrets.webeocIncident }}
{{- $webeocUrl := printf "%s-%s:5432" .Release.Name .Values.global.secrets.webeocUrl }}
{{- $webeocComplaintHistorySeconds := printf "%s-%s:5432" .Release.Name .Values.global.secrets.webeocComplaintHistorySeconds }}
{{- $webeocCronExpression := printf "%s-%s:5432" .Release.Name .Values.global.secrets.databawebeocCronExpressionseAlias }}
{{- $natsHost := printf "%s-%s:5432" .Release.Name .Values.global.secrets.natsHost }}
{{- $backupDir := printf "%s-%s:5432" .Release.Name .Values.global.secrets.backupDir }}

{{- $backupStrategy := printf "%s-%s:5432" .Release.Name .Values.global.secrets.backupStrategy }}
{{- $numBackups := printf "%s-%s:5432" .Release.Name .Values.global.secrets.numBackups }}
{{- $dailyBackups := printf "%s-%s:5432" .Release.Name .Values.global.secrets.dailyBackups }}
{{- $weeklyBackups := printf "%s-%s:5432" .Release.Name .Values.global.secrets.weeklyBackups }}
{{- $monthlyBackups := printf "%s-%s:5432" .Release.Name .Values.global.secrets.monthlyBackups }}
{{- $databaseServiceName := printf "%s-%s:5432" .Release.Name .Values.global.secrets.databaseServiceName }}
{{- $objectstoreAccessKey := printf "%s-%s:5432" .Release.Name .Values.global.secrets.objectstoreAccessKey }}
{{- $objectstoreUrl := printf "%s-%s:5432" .Release.Name .Values.global.secrets.objectstoreUrl }}
{{- $objectstoreBackupDirectory := printf "%s-%s:5432" .Release.Name .Values.global.secrets.objectstoreBackupDirectory }}
{{- $objectstoreBucket := printf "%s-%s:5432" .Release.Name .Values.global.secrets.objectstoreBucket }}
{{- $objectstoreSecretKey := printf "%s-%s:5432" .Release.Name .Values.global.secrets.objectstoreSecretKey }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend
  labels: {{- include "labels" . | nindent 4 }}
  {{- if .Values.global.secrets.persist }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
data:
  # BACKEND Secrets
  POSTGRESQL_PASSWORD: {{ $databasePassword | quote }}
  POSTGRESQL_USER: {{ $databaseUser | b64enc | quote }}
  POSTGRESQL_DATABASE: {{ $databaseName | b64enc | quote }}
  POSTGRESQL_HOST: {{ $hostWithoutPort | b64enc | quote }}
  JWKS_URI: {{ $jwksUri | b64enc | quote }}
  JWT_ISSUER: {{ $jwtIssuer | b64enc | quote }}
  KEYCLOCK_CLIENT_ID: {{ $keycloakClientId | b64enc | quote }}
  BC_GEOCODER_API_CLIENT_ID: {{ $bcGeocoderApiClientId | b64enc | quote }}
  BC_GEOCODER_API_KEY: {{ $bcGeocoderApiKey | b64enc | quote }}
  BC_GEOCODER_API_URL: {{ $bcGeocoderApiUrl | b64enc | quote }}
  CASE_MANAGEMENT_API_URL: {{ $caseManagementApiUrl | b64enc | quote }}
  COMPLAINTS_API_KEY: {{ $caseManagementApiKey | b64enc | quote }}
  POSTGRESQL_ENABLE_LOGGING: {{ $postgresqlEnableLogging | b64enc | quote }}
  COMS_JWT_AUTH_URI: {{ $comsJwtAuthUri | b64enc | quote }}
  CDOGS_URI: {{ $cdogsUri | b64enc | quote }}
  CDOGS_CLIENT_ID: {{ $cdogsClientId | b64enc | quote }}
  CDOGS_CLIENT_SECRET: {{ $cdogsClientSecret | b64enc | quote }}
  # WEBEOC Secrets
  WEBEOC_USERNAME: {{ $webeocUsername | b64enc | quote }}
  WEBEOC_PASSWORD: {{ $webeocPassword | b64enc | quote }}
  WEBEOC_POSITION: {{ $webeocPosition | b64enc | quote }}
  WEBEOC_INCIDENT: {{ $webeocIncident | b64enc | quote }}
  WEBEOC_URL: {{ $webeocUrl | b64enc | quote }}
  WEBEOC_COMPLAINT_HISTORY_SECONDS: {{ $webeocComplaintHistorySeconds | b64enc | quote }}
  WEBEOC_CRON_EXPRESSION: {{ $webeocCronExpression | b64enc | quote }}
  NATS_HOST: {{ $natsHost | b64enc | quote }}
  # BACKUP Secrets
  BACKUP_DIR: {{ $backupDir | b64enc | quote }}
  BACKUP_STRATEGY: {{ $backupStrategy | b64enc | quote }}
  NUM_BACKUPS: {{ $numBackups | b64enc | quote }}
  DAILY_BACKUPS: {{ $dailyBackups | b64enc | quote }}
  WEEKLY_BACKUPS: {{ $weeklyBackups | b64enc | quote }}
  MONTHLY_BACKUPS: {{ $monthlyBackups | b64enc | quote }}
  DATABASE_SERVICE_NAME: {{ $databaseServiceName | b64enc | quote }}
  OBJECTSTORE_ACCESS_KEY: {{ $objectstoreAccessKey | b64enc | quote }}
  OBJECTSTORE_URL: {{ $objectstoreUrl | b64enc | quote }}
  OBJECTSTORE_BACKUP_DIRECTORY: {{ $objectstoreBackupDirectory | b64enc | quote }}
  OBJECTSTORE_BUCKET: {{ $objectstoreBucket | b64enc | quote }}
  OBJECTSTORE_SECRET_KEY: {{ $objectstoreSecretKey | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-flyway
  labels: {{- include "labels" . | nindent 4 }}
  {{- if .Values.global.secrets.persist }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
data:
  FLYWAY_URL: {{ $databaseJDBCURLNoCreds | b64enc | quote }}
  FLYWAY_USER: {{ $databaseUser | b64enc | quote }}
  FLYWAY_PASSWORD: {{ $databasePassword | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-database
  labels: {{- include "labels" . | nindent 4 }}
  {{- if .Values.global.secrets.persist }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
data:
  postgres-password: {{ $databasePassword  | quote }}
  password: {{ $databasePassword | quote }}
{{- end }}
