#!/usr/bin/env bash
# validator-NAME — read-only verdict over collected JSON: OK or an issue string.
#
# A validator checks the OUTPUT of collection snippet(s) and reports a status, so validation
# logic stays separate from fetching. Hand-authored or agent-produced, like cleaned snippets.
#
# Cleaned from SOURCE NAME (a validator).
# Input:     stdin JSON — the merged collection output. Read only the keys you check, and
#            TOLERATE missing data (emit status "skip" rather than failing).
# Read-only: a pure check; no cluster/db access. Idempotent, safe to re-run any time.
# Output:    stdout JSON { check, status, message, docs, sources }
#              check   = the report section this verdict sits next to (e.g. "cluster")
#              status  = ok | warn | error | skip   (skip = the data was not present)
#              message = an OK summary, or the issue string
#              docs    = official-docs URL for the concept checked, so a reader can look it up.
#                        Resolved from the registry (config.yaml status.docs.topics) via the
#                        doc-link shim — never hardcode a URL here; register the topic instead.
#              sources = the workload/object(s) the data came from (e.g. ["pod/db-0"]), read
#                        from the collected JSON, so a reader knows exactly what was inspected.
set -euo pipefail

# Load shared libs: messaging (utils.sh, two dirs up) + this group's doc-link shim — a sibling
# url-shim-<group>.sh generated by scripts/doc_links.py (separator matches the group's; a static
# URL table, so lookups need no yq/config at run time). Both optional — the verdict still emits.
HERE="$(cd "$(dirname "$0")" && pwd)"; GROUP="$(basename "$HERE")"
case "$GROUP" in *_*) SEP=_ ;; *) SEP=- ;; esac
# shellcheck source=/dev/null
. "$HERE/../../utils.sh" 2>/dev/null || true
# shellcheck source=/dev/null
. "$HERE/url${SEP}shim${SEP}${GROUP}.sh" 2>/dev/null || true

CHECK="SECTION"                 # <-- the report section key (.validations.<CHECK>)
data="$(cat)"; data="${data:-null}"

# 1. Extract what you check (one simple jq per value; the `// default` keeps it graceful when
#    the data is missing, and `2>/dev/null || echo …` guards against bad input).
count="$(jq -r '(.SOMEKEY // []) | length' <<<"$data" 2>/dev/null || echo 0)"
# bad="$(jq -r '[(.SOMEKEY // [])[] | select(.field != "good") | .name] | join(", ")' <<<"$data" 2>/dev/null || echo "")"

# 2. Decide status + message.
if [ "$count" -eq 0 ]; then
  status="skip";  message="no data to validate"
elif false; then
  status="error"; message="describe the problem"
elif false; then
  status="warn";  message="describe the warning"
else
  status="ok";    message="all good"
fi

# 3. Docs link for what you checked (looked up by aspect + version in the shim; register the
#    topic in config.yaml status.docs.topics), plus the object(s) the data came from.
docs="$(doc_url ASPECT "${PRODUCT_VERSION:-latest}" 2>/dev/null || true)"
src="$(jq -r '.SOMEKEY_pod // empty' <<<"$data" 2>/dev/null || echo "")"

# 4. Emit the verdict (jq -n escapes the strings safely).
jq -n --arg check "$CHECK" --arg status "$status" --arg message "$message" \
  --arg docs "$docs" --arg src "$src" \
  '{check: $check, status: $status, message: $message, docs: $docs,
    sources: (if $src == "" then [] else ["pod/" + $src] end)}'
