input CreateInvestigationBusinessInput {
  name: String!
  businessReference: String
  contactMethods: [CreateInvestigationContactMethodInput]
  businessIdentifiers: [CreateInvestigationBusinessIdentifierInput]
  aliases: [CreateInvestigationAliasInput]
  addresses: [CreateInvestigationAddressInput]
  contactPeople: [CreateInvestigationBusinessContactInput]
  safetyConcernIndicator: Boolean
  safetyConcernReason: String
}

input UpdateInvestigationBusinessInput {
  name: String!
  contactMethods: [UpdateInvestigationContactMethodInput]
  businessIdentifiers: [UpdateInvestigationBusinessIdentifierInput]
  aliases: [UpdateInvestigationAliasInput]
  addresses: [UpdateInvestigationAddressInput]
  contactPeople: [UpdateInvestigationBusinessContactInput]
  safetyConcernIndicator: Boolean
  safetyConcernReason: String
}
