type Task {
  taskIdentifier: String!
  investigationIdentifier: String!
  investigationLabel: String
  taskStatusCode: String!
  assignedUserIdentifier: String
  createdByUserIdentifier: String!
  createdDate: DateTime!
  updatedDate: DateTime
  taskNumber: Int!
  description: String
  activeIndicator: Boolean!
  taskCategoryTypeCode: String!
  subject: String!
  dueDate: DateTime!
}

input CreateUpdateTaskInput {
  taskIdentifier: String
  investigationIdentifier: String
  taskStatusCode: String
  assignedUserIdentifier: String
  appUserIdentifier: String
  description: String
  taskCategoryTypeCode: String
  subject: String
  dueDate: DateTime
}
