export const ACTION_TYPE_CODES = {
  COMPASSESS: "COMPASSESS",
  COSPRVANDEDU: "COSPRV&EDU",
  PRKPRVANDEDU: "PRKPRV&EDU",
  EQUIPMENT: "EQUIPMENT",
  CASEACTION: "CASEACTION",
  WILDLIFE: "WILDLIFE",
  CEEBACTION: "CEEBACTION",
  CAT1ASSESS: "CAT1ASSESS",
};
