{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  automountServiceAccountToken: false
  strategy:
    type: {{ .Values.backend.deploymentStrategy }}
  {{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicaCount }}
  {{- else if and (not .Values.backend.autoscaling.enabled) (eq .Release.Namespace .Values.global.testNamespace) }}
  replicas: {{ .Values.global.testNamespaceDeploymentReplicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        prometheus.io/scrape: 'true'
        prometheus.io/port: '3000'
        prometheus.io/path: '/api/metrics'
      labels:
        {{- include "backend.labels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      {{- if .Values.backend.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.backend.podSecurityContext | nindent 12 }}
      {{- end }}
      initContainers:
        - name: {{ include "backend.fullname" . }}-init
          image: "{{ .Values.global.registry }}/{{ .Values.global.repository }}/migrations:{{ .Values.global.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ default "Always" .Values.backend.imagePullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-flyway
          env:
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
            - name: FLYWAY_BASELINE_ON_MIGRATE
              value: "true"
            - name: FLYWAY_DEFAULT_SCHEMA
              value: "public"
            - name: FLYWAY_CONNECT_RETRIES
              value: "10"
            - name: FLYWAY_LOCATIONS
              value: "{{- if eq .Release.Namespace "c1c7ed-dev" -}}{{ .Values.global.secrets.flywayLocations.dev }}{{- else if eq .Release.Namespace "c1c7ed-test" -}}{{ .Values.global.secrets.flywayLocations.test }}{{- else if eq .Release.Namespace "c1c7ed-prod" -}}{{ .Values.global.secrets.flywayLocations.prod }}{{- else -}}filesystem:./flyway/sql{{- end }}"
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 100Mi
      containers:
        - name: {{ include "backend.fullname" . }}
          {{- if .Values.backend.securityContext }}
          securityContext:
            {{- toYaml .Values.backend.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.global.registry }}/{{ .Values.global.repository }}/backend:{{ .Values.global.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ default "Always" .Values.backend.imagePullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-backend
          env:
            - name: LOG_LEVEL
              value: info
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.targetPort }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /api
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 30
          livenessProbe:
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              path: /api
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
          resources: # this is optional
            limits:
              cpu: 150m
              memory: 150Mi
            requests:
              cpu: 50m
              memory: 75Mi
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - {{ include "backend.fullname" . }}
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"

{{- end }}