export enum PartyExternalIds {
  FISH_AND_WILDLIFE_ID = "FWID",
  CLIENT_ID = "CLID",
  WINCHESTER_ID = "WIN",
  CORE_NUMBER = "CORE",
  STATUS_INDIAN_NUMBER = "SIN",
  FINGERPRINT_SERIAL_NUMBER = "FPS",
}
