import { Mapper } from "@automapper/core";
import { mapPrismaContactMethodToContactMethod } from "../shared/contact_method/dto/contact_method";
import { mapPrismaPersonToPerson } from "../shared/person/dto/person";
import { mapPrismaParkToPark } from "../shared/park/dto/park";
import { mapPrismaParkAreaToParkArea } from "../shared/park/dto/park_area";
import { mapPrismaParkAreaMappingToParkAreaMapping } from "../shared/park/dto/park_area_mapping";
import { mapPrismaAgencyCodeToAgencyCode } from "../shared/agency_code/dto/agency_code";
import { mapPrismaCaseStatusCodeToCaseStatusCode } from "../shared/case_status_code/dto/case_status_code";
import { mapPrismaCaseActivityTypeCodeToCaseActivityTypeCode } from "../shared/case_activity_type_code/dto/case_activity_type_code";
import { mapPrismaCaseActivityToCaseActivity } from "../shared/case_activity/dto/case_activity";
import { mapPrismaCaseFileToCaseFile } from "../shared/case_file/dto/case_file";
import { mapPrismaInvestigationToInvestigation } from "../investigation/investigation/dto/investigation";
import { mapPrismaInvestigationStatusCodeToInvestigationStatusCode } from "../investigation/investigation_status_code/dto/investigation_status_code";
import { mapPrismaInspectionToInspection } from "../inspection/inspection/dto/inspection";
import { mapPrismaInspectionStatusCodeToInspectionStatusCode } from "../inspection/inspection_status_code/dto/inspection_status_code";
import { mapPrismaPartyToParty } from "src/shared/party/dto/party";
import { mapPrismaBusinessToBusiness } from "src/shared/business/dto/business";
import { mapPrismaPartyTypeCodeToPartyTypeCode } from "../shared/party_type_code/dto/party_type_code";
import { mapPrismaEventToEvent } from "../shared/event/dto/event";
import { mapPrismaEventVerbTypeCodeToEventVerbTypeCode } from "../shared/event_verb_type_code/dto/event_verb_type_code";
import { mapPrismaEventEntityTypeCodeToEventEntityTypeCode } from "../shared/event_entity_type_code/dto/event_entity_type_code";

export const initializeMappings = (mapper: Mapper) => {
  mapPrismaContactMethodToContactMethod(mapper);
  mapPrismaPersonToPerson(mapper);
  mapPrismaParkToPark(mapper);
  mapPrismaParkAreaToParkArea(mapper);
  mapPrismaParkAreaMappingToParkAreaMapping(mapper);
  mapPrismaAgencyCodeToAgencyCode(mapper);
  mapPrismaCaseStatusCodeToCaseStatusCode(mapper);
  mapPrismaCaseActivityTypeCodeToCaseActivityTypeCode(mapper);
  mapPrismaCaseActivityToCaseActivity(mapper);
  mapPrismaCaseFileToCaseFile(mapper);
  mapPrismaInvestigationToInvestigation(mapper);
  mapPrismaInvestigationStatusCodeToInvestigationStatusCode(mapper);
  mapPrismaInspectionToInspection(mapper);
  mapPrismaInspectionStatusCodeToInspectionStatusCode(mapper);
  mapPrismaBusinessToBusiness(mapper);
  mapPrismaPartyToParty(mapper);
  mapPrismaPartyTypeCodeToPartyTypeCode(mapper);
  mapPrismaEventVerbTypeCodeToEventVerbTypeCode(mapper);
  mapPrismaEventEntityTypeCodeToEventEntityTypeCode(mapper);
  mapPrismaEventToEvent(mapper);
};
