name: Cypress Tests
on:
#  workflow_run:
#      workflows: [Pull Request]
#      types:
#        - completed
  pull_request:
jobs:
 Cypress-Test:
   env:
      DOMAIN: apps.silver.devops.gov.bc.ca
      PREFIX: ${{ github.event.repository.name }}-${{ github.event.number }}
   runs-on: ubuntu-latest
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v3
 
     - name: Run Cypress Test
       uses: cypress-io/github-action@v5
       with:
         config: baseUrl=https://${{ env.PREFIX }}-frontend.${{ env.DOMAIN }}
         working-directory: ./frontend
         command: npx cypress run
        
     - name: Upload Artifacts
       uses: actions/upload-artifact@v2
       if: always()
       with:
          name: cypress-videos
          path: /home/runner/work/nr-compliance-enforcement/nr-compliance-enforcement/frontend/cypress/videos/