# Deploys hotfixes to the test environment
name: Merge-Hotfix

on:
  push:
    branches: [hotfix]
    paths-ignore:
      - "*.md"
      - ".github/**"
      - ".github/graphics/**"
      - "!.github/workflows/**"
  workflow_dispatch:
    inputs:
      pr_no:
        description: "PR-numbered container set to deploy"
        type: number
        required: true

concurrency:
  # Do not interrupt previous workflows
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  vars:
    name: Set Variables
    outputs:
      pr: ${{ steps.pr.outputs.pr }}
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    steps:
      # Get PR number for squash merges to main
      - name: PR Number
        id: pr
        uses: bcgov/action-get-pr@v0.0.1

  # https://github.com/bcgov/quickstart-openshift-helpers
  deploy-hotfix:
    name: Deploy (hotfix)
    needs: vars
    uses: bcgov/quickstart-openshift-helpers/.github/workflows/.deployer.yml@v0.5.0
    secrets:
      oc_namespace: ${{ secrets.OC_NAMESPACE }}
      oc_token: ${{ secrets.OC_TOKEN }}
    with:
      environment: hotfix
      tag: ${{ needs.vars.outputs.pr }}

  promote:
    name: Promote Images
    needs: [deploy-hotfix, vars]
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: [migrations, backend, frontend, webeoc]
    timeout-minutes: 1
    steps:
      - uses: shrink/actions-docker-registry-tag@v4
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.package }}
          target: ${{ needs.vars.outputs.pr }}
          tags: hotfix
