name: Create New Tag on Release Branch Creation

on:
  create:

jobs:
  bump_minor_version:
    name: Bump Minor Version and Create New Tag
    runs-on: ubuntu-22.04
    permissions:
      contents: "write"
      packages: "write"
      actions: "read"
    # Only trigger for main release branches
    if: startsWith(github.ref, 'refs/heads/release/')
    steps:
      - name: Authenticate GitHub App and Get Token
        id: get_gh_app_token
        uses: ./.github/actions/get-gh-app-token
        with:
          github_app_id: ${{ vars.TEAM_WOLVERINE_GITHUB_APP_ID }}
          github_app_private_key: ${{ secrets.TEAM_WOLVERINE_GITHUB_APP_PRIVATE_KEY }}

      - name: Install npm
        run: sudo apt-get install -y npm

      # Bump the minor version (which resets the patch to 0)
      - name: Bump minor version
        id: bump_version
        run: |
          cd frontend
          npm version minor
          echo "::set-output name=new_version::$(npm pkg get version | tr -d '"')"
          new_v=$(npm pkg get version | tr -d '"')
          echo "Frontend package.json version updated to $new_v"

          cd ../backend
          npm version $new_v --no-git-tag-version
          echo "Backend package.json version updated to $new_v"

          cd ../webeoc
          npm version $new_v --no-git-tag-version
          echo "WebEOC package.json version updated to $new_v"

          cd ..

      - name: Commit and Push Version Update
        env:
          GH_TOKEN: ${{ steps.get_gh_app_token.outputs.token }}
        run: |
          git add frontend/package.json backend/package.json webeoc/package.json
          git commit -m 'chore: bump version to ${{ steps.bump_version.outputs.new_version }}'
          git push origin HEAD:${{ github.ref }}

      # Create a new tag with the bumped minor version
      - name: Create and push the new tag
        env:
          GH_TOKEN: ${{ steps.get_gh_app_token.outputs.token }}
        run: |
          git tag "v${{ steps.bump_version.outputs.new_version }}"
          git push origin "v${{ steps.bump_version.outputs.new_version }}"
