name: Create New Tag on Release Branch Creation

on:
  create:

jobs:
  bump_minor_version:
    name: Bump Minor Version and Create New Tag
    runs-on: ubuntu-22.04
    # Only trigger for main release branches
    if: startsWith(github.ref, 'refs/heads/release/')
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          fetch-tags: true

      - name: Install npm
        run: sudo apt-get install -y npm

      # Bump the minor version (which resets the patch to 0)
      - name: Bump minor version
        id: bump_version
        run: |
          cd frontend
          npm version minor
          echo "::set-output name=new_version::$(npm pkg get version | tr -d '"')"
          new_v=$(npm pkg get version | tr -d '"')
          echo "Frontend package.json version updated to $new_v"

          cd ../backend
          npm version $new_v --no-git-tag-version
          echo "Backend package.json version updated to $new_v"

          cd ../webeoc
          npm version $new_v --no-git-tag-version
          echo "WebEOC package.json version updated to $new_v"

          cd ..

      - name: Commit and Push Version Update
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add frontend/package.json backend/package.json webeoc/package.json
          git commit -m 'chore: bump version to ${{ steps.bump_version.outputs.new_version }}'
          git push origin HEAD:${{ github.ref }}

      # Create a new tag with the bumped minor version
      - name: Create and push the new tag
        run: |
          git tag "v${{ steps.bump_version.outputs.new_version }}"
          git push origin "v${{ steps.bump_version.outputs.new_version }}"
