name: Generate Schemaspy Docs
on:
  workflow_dispatch:

  pull_request:   
#  push:
#    branches:
#      - main

jobs:
  generate_schemaspy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: default
          POSTGRES_USER: user
          POSTGRES_PASSWORD: default
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@master
      - uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: jdbc:postgresql://postgres:5432/default
          user: user
          password: default
        env:
          FLYWAY_VALIDATE_MIGRATION_NAMING: true
          FLYWAY_LOCATIONS: filesystem:./backend/db/migrations
      - name: Create Output Folder
        run: |
          mkdir output
          chmod a+rwx -R output
      - name: Run Schemaspy
        run: docker run --network host -v "$PWD/output:/output" schemaspy/schemaspy:snapshot -t pgsql -db default -host 127.0.0.1 -port 5432 -u user -p default
      - name: Deploy to Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: output
          target-folder: schemaspy