name: Generate Schemaspy Docs
on:
  workflow_dispatch:

  pull_request:   
#  push:
#    branches:
#      - main

jobs:
  generate-schema-spy:
    name: Generate SchemaSpy Documentation
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgis/postgis
        env:
          POSTGRES_DB: default
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: default
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - uses: joshuaavalon/flyway-action@v3.0.0
        name: Generate SchemaSpy docs for node backend
        with:
          url: jdbc:postgresql://postgres:5432/postgres
          user: postgres
          password: default
        env:
          FLYWAY_VALIDATE_MIGRATION_NAMING: true
          FLYWAY_LOCATIONS: filesystem:./backend/db/migrations
          FLYWAY_DEFAULT_SCHEMA: "public"
      - name: Create Output Folder
        run: |
          mkdir output
          chmod a+rwx -R output
      - name: Run Schemaspy
        run: docker run --network host -v "$PWD/output:/output" schemaspy/schemaspy:6.2.4 -t pgsql -db default -host 127.0.0.1 -port 5432 -u postgres -p default -schemas public
      - name: Deploy to Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: output
          target-folder: schemaspy